import assert from 'node:assert/strict';
import {spawn,type ChildProcess} from 'node:child_process';
import {mkdtempSync,rmSync,writeFileSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {WsClient} from 'tsrpc';
import {serviceProto} from '../apps/shared/protocols/serviceProto';
import {AccountStore} from '../apps/server/src/account-store';
import type {MsgRoomSnapshot,MsgRoomEvent} from '../apps/shared/protocols';
async function main(){
 const playingBuyOnly=process.argv.includes('--playing-buy-only');
 const runId=new Date().toISOString().replace(/[:.]/g,'-'),output='recovery/output/ammo11-purchase-network-'+(playingBuyOnly?'playing-buy-':'')+runId,dir=mkdtempSync(join(tmpdir(),'cdtank-ammo11-purchase-')),database=join(dir,'accounts.sqlite'),port=3225;let server:ChildProcess|undefined,log='';
 const clients=Array.from({length:4},()=>new WsClient(serviceProto,{server:`ws://127.0.0.1:${port}`,logger:undefined,heartbeat:{interval:5000,timeout:10000}}));const snapshots:MsgRoomSnapshot[][]=clients.map(()=>[]),events:MsgRoomEvent[][]=clients.map(()=>[]);clients.forEach((c,i)=>{c.listenMsg('RoomSnapshot',s=>{snapshots[i].push(s);});c.listenMsg('RoomEvent',e=>{events[i].push(e);});});
 async function wait(f:()=>boolean,ms=10000){const end=Date.now()+ms;while(!f()&&Date.now()<end)await new Promise(r=>setTimeout(r,25));assert(f(),log.slice(-1000));}async function stop(){if(server?.exitCode===null&&server.signalCode===null){const end=new Promise<void>(r=>server!.once('exit',()=>r()));server.kill();await end;}}async function start(){const startOffset=log.length;server=spawn(process.execPath,['--import','tsx','apps/server/src/index.ts'],{env:{...process.env,PORT:String(port),ACCOUNT_DB_PATH:database,MATCH_TIME_LIMIT_SECONDS:'30'},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>{log+=String(d);});server.stderr!.on('data',d=>{log+=String(d);});await wait(()=>log.slice(startOffset).includes(`Server started at ${port}.`));}
 const latest=(i=0)=>snapshots[i].at(-1)!;const evidence:{[key:string]:unknown}={status:'RUNNING',runId,port,scope:playingBuyOnly?'Directed rebuilt shop PLAYING BUY refusal with actual BUY-created instance and normal Ready; unchanged balances and inventory':'Rebuilt paid2011 MONEY50/TOKENS50 purchase allocation and AI authority; empty starting inventory, explicit experimental profile funding, actual BUY-created instances, Kitbag/Ready/Autopilot, two natural30s CPU rounds and same-account server restart'};
 try{
 await start();const accounts:{accountId:string;token:string}[]=[];for(const c of clients.slice(0,3)){assert((await c.connect()).isSucc);const a=await c.callApi('Account',{});assert(a.isSucc);accounts.push(a.res);}
 const native=JSON.parse(readFileSync('recovery/output/world-role-attributes-native.json','utf8')).rows.find((r:{tankId:number;part:number})=>r.tankId===1&&r.part===0);const store=new AccountStore(database);try{for(const [index,owner] of accounts.slice(0,2).entries()){
 const fields=(v:Record<string,number>)=>new Map(Object.entries(v).map(([k,v])=>[Number(k),v]));const equipment={name:'明确导入原战车',fields:fields(native.equipment)},base={name:'明确导入原宠物',fields:fields(native.base)};equipment.fields.set(0x1c,72);equipment.fields.set(0x24,1);equipment.fields.set(0x28,index?10021:10011);equipment.fields.set(0x2c,index?10022:10012);equipment.fields.set(0x30,index?10023:10013);store.replaceRoleRecords(owner.accountId,{base:[base],equipment:[equipment]});assert.equal(store.inventory(owner.accountId).records.length,0);const bytes=new Uint8Array(0x170),view=new DataView(bytes.buffer);view.setUint32(0xa8,72,true);view.setUint32(0xa4,base.fields.get(0)!,true);view.setUint32(0x70,index===0?200:20,true);view.setUint32(0x74,200,true);store.replaceRoleProfile(owner.accountId,{bytes,strings:['','']});}}finally{store.close();}
 const query=await clients[0].callApi('Shop',{operation:'QUERY'});assert(query.isSucc);assert.equal(query.res.items.find(i=>i.itemTableId===2011)!.moneyPrice,50);assert.equal(query.res.items.find(i=>i.itemTableId===2011)!.tokenPrice,50);const buy={operation:'BUY' as const,itemTableId:2011,quantity:2,currency:'MONEY' as const,requestId:'ammo11_money_0001'};const paid=await clients[0].callApi('Shop',buy);assert(paid.isSucc);assert.equal(paid.res.money,100);assert.equal(paid.res.purchased!.ownedQuantity,2);const instanceId=paid.res.purchased!.instanceId;evidence.purchase=paid.res;
 const replay=await clients[0].callApi('Shop',buy);assert(replay.isSucc&&replay.res.replayed);assert.equal(replay.res.money,100);const conflict=await clients[0].callApi('Shop',{...buy,quantity:1});assert(!conflict.isSucc);evidence.idempotency={replay,conflict};
 const rejected=await clients[1].callApi('Shop',{...buy,requestId:'ammo11_shortage_0001'});assert(!rejected.isSucc);const empty=await clients[1].callApi('Inventory',{});assert(empty.isSucc&&empty.res.records.length===0);evidence.insufficient=rejected;
 const tokenPaid=await clients[1].callApi('Shop',{...buy,currency:'TOKENS',requestId:'ammo11_tokens_0001'});assert(tokenPaid.isSucc);assert.equal(tokenPaid.res.tokens,100);assert.equal(tokenPaid.res.money,20);evidence.tokensPurchase=tokenPaid.res;
 assert((await clients[0].callApi('Kitbag',{operation:'ASSIGN',slot:1,instanceId})).isSucc);assert((await clients[1].callApi('Kitbag',{operation:'ASSIGN',slot:1,instanceId:tokenPaid.res.purchased!.instanceId})).isSucc);evidence.fixture={source:'world-role-attributes-native.json tank1/part0',initialInventory:'empty',experimentalProfileMoney:[200,20],experimentalProfileTokens:[200,200],itemTableId:2011,boughtQuantity:2,instances:[instanceId,tokenPaid.res.purchased!.instanceId]};
 const created=await clients[0].callApi('CreateRoom',{mode:4,mapId:7,name:'耗弹甲',tankId:1,roomName:'2011耗弹验收'});assert(created.isSucc);const roomId=created.res.room.id,ownerId=created.res.playerId;assert((await clients[1].callApi('Join',{roomId,clientId:'ignored',name:'耗弹乙',tankId:1})).isSucc);assert((await clients[0].callApi('Cpu',{round:1,operation:'ADD',tankId:1})).isSucc);
 if(!playingBuyOnly)for(const c of clients.slice(0,2))assert((await c.callApi('Autopilot',{round:1,enabled:true})).isSucc);for(const c of clients.slice(0,2))assert((await c.callApi('Ready',{round:1,isReady:true})).isSucc);await wait(()=>snapshots[0].some(s=>s.phase==='PLAYING'));evidence.initial=snapshots[0].find(s=>s.phase==='PLAYING');
 const beforeBlockedInventory=await clients[0].callApi('Inventory',{});assert(beforeBlockedInventory.isSucc);const beforeBattleBuy=await clients[0].callApi('Shop',{operation:'QUERY'});assert(beforeBattleBuy.isSucc);const blockedBuy=await clients[0].callApi('Shop',{...buy,requestId:'ammo11_playing_buy_0001'});evidence.blockedBuy=blockedBuy;assert(!blockedBuy.isSucc);assert.equal(blockedBuy.err.code,'SHOP_REJECTED');assert.equal(blockedBuy.err.message,'请在准备阶段购买道具');const afterBattleBuy=await clients[0].callApi('Shop',{operation:'QUERY'});assert(afterBattleBuy.isSucc);assert.equal(afterBattleBuy.res.money,beforeBattleBuy.res.money);assert.equal(afterBattleBuy.res.tokens,beforeBattleBuy.res.tokens);const afterBlockedInventory=await clients[0].callApi('Inventory',{});assert(afterBlockedInventory.isSucc);assert.equal(afterBlockedInventory.res.records.length,1);assert.equal(afterBlockedInventory.res.records[0].instanceId,instanceId);if(playingBuyOnly)assert.deepEqual(afterBlockedInventory.res,beforeBlockedInventory.res);evidence.playingBuy={blockedBuy,beforeInventory:beforeBlockedInventory.res,beforeBalance:{money:beforeBattleBuy.res.money,tokens:beforeBattleBuy.res.tokens},afterBalance:{money:afterBattleBuy.res.money,tokens:afterBattleBuy.res.tokens},inventory:afterBlockedInventory.res};if(playingBuyOnly){evidence.scope='Directed rebuilt shop PLAYING BUY refusal: actual purchased instance, normal Ready room; blocked new request leaves balances and complete Inventory unchanged';for(const c of clients.slice(0,2))assert((await c.callApi('Leave',{roomId,round:1})).isSucc);evidence.status='PASS';console.log(JSON.stringify({status:'PASS',output,scope:evidence.scope}));return;}
 const owner=()=>latest().players.find(p=>p.id===ownerId)!;const countFire=(id=ownerId,i=0)=>events[i].filter(e=>e.type==='fire'&&e.playerId===id).length;
 await wait(()=>events[0].filter(e=>e.type==='ammoConsumed'&&e.playerId===ownerId).length===2,25000);const inventory=await clients[0].callApi('Inventory',{});assert(inventory.isSucc);assert.equal(inventory.res.records[0].ownedQuantity,0);assert.equal(inventory.res.records[0].battleQuantity,0);evidence.depletedInventory=inventory.res;
 await wait(()=>events[0].some(e=>e.type==='fire'&&e.playerId===ownerId&&e.skillId===2001),25000);evidence.afterDefault=latest();const initialOwner=(evidence.initial as MsgRoomSnapshot).players.find(p=>p.id===ownerId)!;const maxDistance=Math.max(...snapshots[0].map(s=>{const p=s.players.find(p=>p.id===ownerId)!;return Math.hypot(p.x-initialOwner.x,p.z-initialOwner.z);}));evidence.observedMotion={ownerId,maxDistanceAtDefault:maxDistance,scope:'Observed distance only; stationary close-target firing is legal, no navigation acceptance assertion'};
 const persisted=()=>{const s=new AccountStore(database);try{return s.inventory(accounts[0].accountId);}finally{s.close();}};assert.equal(persisted().records[0].ownedQuantity,0);
 await wait(()=>latest().phase==='FINISHED',40000);evidence.finished=latest();assert(events[0].some(e=>e.type==='fire'&&e.playerId!==ownerId));assert(events[0].some(e=>e.type==='hit'));for(const c of clients.slice(0,2))assert((await c.callApi('Rematch',{round:1})).isSucc);await wait(()=>latest().phase==='PLAYING'&&latest().match?.round===2);evidence.rematch=latest();const inv2=await clients[0].callApi('Inventory',{});assert(inv2.isSucc);assert.equal(inv2.res.records[0].ownedQuantity,0);assert.equal(inv2.res.records[0].battleQuantity,0);evidence.round2Inventory=inv2.res;await wait(()=>latest().phase==='FINISHED'&&latest().match?.round===2,40000);evidence.round2Finished=latest();
 const sharedEvents=events[0].filter(e=>['ammoConsumed','fire','itemRejected'].includes(e.type)&&e.playerId===ownerId),peerEvents=events[1].filter(e=>['ammoConsumed','fire','itemRejected'].includes(e.type)&&e.playerId===ownerId);assert.deepEqual(sharedEvents,peerEvents);assert.deepEqual(sharedEvents.filter(e=>e.type==='ammoConsumed').map(e=>e.value),[1,0]);assert.equal(sharedEvents.filter(e=>e.type==='fire'&&e.skillId===2011).length,2);const peerId=(evidence.initial as MsgRoomSnapshot).players.find(p=>!p.isCpu&&p.id!==ownerId)!.id;for(const id of [ownerId,peerId]){const own=events[0].filter(e=>e.playerId===id);assert.equal(own.filter(e=>e.type==='fire'&&e.skillId===2011).length,2);assert.deepEqual(own.filter(e=>e.type==='ammoConsumed').map(e=>e.value),[1,0]);assert(own.some(e=>e.type==='fire'&&e.skillId===2001));}assert.equal(events[2].filter(e=>e.roomId===roomId).length,0);
 for(const c of clients.slice(0,2))assert((await c.callApi('Leave',{roomId,round:2})).isSucc);await Promise.all(clients.map(c=>c.disconnect()));await stop();await start();const restored=[];for(let i=0;i<2;i++){assert((await clients[i].connect()).isSucc);assert((await clients[i].callApi('Account',{token:accounts[i].token})).isSucc);const inventory=await clients[i].callApi('Inventory',{});assert(inventory.isSucc);assert.equal(inventory.res.records[0].ownedQuantity,0);assert.equal(inventory.res.hotkeys[0],i===0?instanceId:tokenPaid.res.purchased!.instanceId);const balance=await clients[i].callApi('Shop',{operation:'QUERY'});assert(balance.isSucc);assert.equal(balance.res.money,i===0?100:20);assert.equal(balance.res.tokens,i===0?200:100);restored.push({...inventory.res,balance:{money:balance.res.money,tokens:balance.res.tokens}});}evidence.actualRestart=restored;const reentry=await clients[0].callApi('CreateRoom',{mode:4,mapId:7,name:'恢复账户',tankId:1,roomName:'恢复库存验收'});assert(reentry.isSucc);assert((await clients[0].callApi('Ready',{round:1,isReady:true})).isSucc);await wait(()=>latest().roomId===reentry.res.room.id&&latest().phase==='PLAYING');const rebound=await clients[0].callApi('Inventory',{});assert(rebound.isSucc);assert.equal(rebound.res.records[0].battleQuantity,0);evidence.restartReentryInventory=rebound.res;assert((await clients[0].callApi('Leave',{roomId:reentry.res.room.id,round:1})).isSucc);evidence.status='PASS';console.log(JSON.stringify({status:'PASS',output,ownerFire:countFire(),consumed:[1,0],restartOwned:restored.map(i=>i.records[0].ownedQuantity)}));
 }catch(error){evidence.status='FAIL';evidence.error=String(error);throw error;}finally{evidence.snapshots=snapshots;evidence.events=events;await Promise.allSettled(clients.map(c=>c.disconnect()));await stop();writeFileSync(output+'.json',JSON.stringify(evidence,null,2)+'\n');writeFileSync(output+'.log',log);rmSync(dir,{recursive:true,force:true});}
}main().catch(e=>{console.error(e);process.exitCode=1;});
