import assert from 'node:assert/strict';
import {spawn,type ChildProcess} from 'node:child_process';
import {mkdtempSync,rmSync,writeFileSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {WsClient} from 'tsrpc';
import {serviceProto} from '../apps/shared/protocols/serviceProto';
import {AccountStore} from '../apps/server/src/account-store';
import type {MsgRoomSnapshot,MsgRoomEvent} from '../apps/shared/protocols';
async function main(){
 const runId=new Date().toISOString().replace(/[:.]/g,'-'),output='recovery/output/ammo-ai-network-'+runId,dir=mkdtempSync(join(tmpdir(),'cdtank-ammo11-consumption-')),database=join(dir,'accounts.sqlite'),port=3223;let server:ChildProcess|undefined,log='';
 const clients=Array.from({length:4},()=>new WsClient(serviceProto,{server:`ws://127.0.0.1:${port}`,logger:undefined,heartbeat:{interval:5000,timeout:10000}}));const snapshots:MsgRoomSnapshot[][]=clients.map(()=>[]),events:MsgRoomEvent[][]=clients.map(()=>[]);clients.forEach((c,i)=>{c.listenMsg('RoomSnapshot',s=>{snapshots[i].push(s);});c.listenMsg('RoomEvent',e=>{events[i].push(e);});});
 async function wait(f:()=>boolean,ms=10000){const end=Date.now()+ms;while(!f()&&Date.now()<end)await new Promise(r=>setTimeout(r,25));assert(f(),log.slice(-1000));}async function stop(){if(server?.exitCode===null&&server.signalCode===null){const end=new Promise<void>(r=>server!.once('exit',()=>r()));server.kill();await end;}}async function start(){const startOffset=log.length;server=spawn(process.execPath,['--import','tsx','apps/server/src/index.ts'],{env:{...process.env,PORT:String(port),ACCOUNT_DB_PATH:database,MATCH_TIME_LIMIT_SECONDS:'30'},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>{log+=String(d);});server.stderr!.on('data',d=>{log+=String(d);});await wait(()=>log.slice(startOffset).includes(`Server started at ${port}.`));}
 const latest=(i=0)=>snapshots[i].at(-1)!;const evidence:{[key:string]:unknown}={status:'RUNNING',runId,port,scope:'Rebuilt finite2011 owned/battle2; actual index normal accounts/Kitbag/room/Ready/Autopilot; two natural30s CPU rounds, actual restart; only Autopilot APIs allow AI to choose ammo and emit ordinary movement/fire inputs; no injected life/positions/events/results'};
 try{
 await start();const accounts:{accountId:string;token:string}[]=[];for(const c of clients.slice(0,3)){assert((await c.connect()).isSucc);const a=await c.callApi('Account',{});assert(a.isSucc);accounts.push(a.res);}
 const native=JSON.parse(readFileSync('recovery/output/world-role-attributes-native.json','utf8')).rows.find((r:{tankId:number;part:number})=>r.tankId===1&&r.part===0);const store=new AccountStore(database);try{for(const [index,owner] of accounts.slice(0,2).entries()){
 const fields=(v:Record<string,number>)=>new Map(Object.entries(v).map(([k,v])=>[Number(k),v]));const equipment={name:'明确导入原战车',fields:fields(native.equipment)},base={name:'明确导入原宠物',fields:fields(native.base)};equipment.fields.set(0x1c,72);equipment.fields.set(0x24,1);equipment.fields.set(0x28,index?10021:10011);equipment.fields.set(0x2c,index?10022:10012);equipment.fields.set(0x30,index?10023:10013);store.replaceRoleRecords(owner.accountId,{base:[base],equipment:[equipment]});store.replaceInventory(owner.accountId,[{instanceId:77,itemTableId:2011,ownedQuantity:2,battleQuantity:2,state:0,field8:0,float24Bits:0,float28Bits:0,float2cBits:0}]);const bytes=new Uint8Array(0x170),view=new DataView(bytes.buffer);view.setUint32(0xa8,72,true);view.setUint32(0xa4,base.fields.get(0)!,true);store.replaceRoleProfile(owner.accountId,{bytes,strings:['','']});}}finally{store.close();}
 for(const c of clients.slice(0,2))assert((await c.callApi('Kitbag',{operation:'ASSIGN',slot:1,instanceId:77})).isSucc);evidence.fixture={source:'world-role-attributes-native.json tank1/part0;browser-combat-muzzle-2011',instanceId:77,itemTableId:2011,ownedQuantity:2,battleQuantity:2,kitbagSlot:1,battleKey:2};
 const created=await clients[0].callApi('CreateRoom',{mode:4,mapId:7,name:'耗弹甲',tankId:1,roomName:'2011耗弹验收'});assert(created.isSucc);const roomId=created.res.room.id,ownerId=created.res.playerId;assert((await clients[1].callApi('Join',{roomId,clientId:'ignored',name:'耗弹乙',tankId:1})).isSucc);assert((await clients[0].callApi('Cpu',{round:1,operation:'ADD',tankId:1})).isSucc);
 for(const c of clients.slice(0,2))assert((await c.callApi('Autopilot',{round:1,enabled:true})).isSucc);for(const c of clients.slice(0,2))assert((await c.callApi('Ready',{round:1,isReady:true})).isSucc);await wait(()=>snapshots[0].some(s=>s.phase==='PLAYING'));evidence.initial=snapshots[0].find(s=>s.phase==='PLAYING');
 const owner=()=>latest().players.find(p=>p.id===ownerId)!;const countFire=(id=ownerId,i=0)=>events[i].filter(e=>e.type==='fire'&&e.playerId===id).length;
 await wait(()=>events[0].filter(e=>e.type==='ammoConsumed'&&e.playerId===ownerId).length===2,25000);const inventory=await clients[0].callApi('Inventory',{});assert(inventory.isSucc);assert.equal(inventory.res.records[0].ownedQuantity,0);assert.equal(inventory.res.records[0].battleQuantity,0);evidence.depletedInventory=inventory.res;
 await wait(()=>events[0].some(e=>e.type==='fire'&&e.playerId===ownerId&&e.skillId===2001),25000);evidence.afterDefault=latest();const initialOwner=(evidence.initial as MsgRoomSnapshot).players.find(p=>p.id===ownerId)!;const maxDistance=Math.max(...snapshots[0].map(s=>{const p=s.players.find(p=>p.id===ownerId)!;return Math.hypot(p.x-initialOwner.x,p.z-initialOwner.z);}));evidence.observedMotion={ownerId,maxDistanceAtDefault:maxDistance,scope:'Observed distance only; stationary close-target firing is legal, no navigation acceptance assertion'};
 const persisted=()=>{const s=new AccountStore(database);try{return s.inventory(accounts[0].accountId);}finally{s.close();}};assert.equal(persisted().records[0].ownedQuantity,0);
 await wait(()=>latest().phase==='FINISHED',40000);evidence.finished=latest();assert(events[0].some(e=>e.type==='fire'&&e.playerId!==ownerId));assert(events[0].some(e=>e.type==='hit'));for(const c of clients.slice(0,2))assert((await c.callApi('Rematch',{round:1})).isSucc);await wait(()=>latest().phase==='PLAYING'&&latest().match?.round===2);evidence.rematch=latest();const inv2=await clients[0].callApi('Inventory',{});assert(inv2.isSucc);assert.equal(inv2.res.records[0].ownedQuantity,0);assert.equal(inv2.res.records[0].battleQuantity,0);evidence.round2Inventory=inv2.res;await wait(()=>latest().phase==='FINISHED'&&latest().match?.round===2,40000);evidence.round2Finished=latest();
 const sharedEvents=events[0].filter(e=>['ammoConsumed','fire','itemRejected'].includes(e.type)&&e.playerId===ownerId),peerEvents=events[1].filter(e=>['ammoConsumed','fire','itemRejected'].includes(e.type)&&e.playerId===ownerId);assert.deepEqual(sharedEvents,peerEvents);assert.deepEqual(sharedEvents.filter(e=>e.type==='ammoConsumed').map(e=>e.value),[1,0]);assert.equal(sharedEvents.filter(e=>e.type==='fire'&&e.skillId===2011).length,2);const peerId=(evidence.initial as MsgRoomSnapshot).players.find(p=>!p.isCpu&&p.id!==ownerId)!.id;for(const id of [ownerId,peerId]){const own=events[0].filter(e=>e.playerId===id);assert.equal(own.filter(e=>e.type==='fire'&&e.skillId===2011).length,2);assert.deepEqual(own.filter(e=>e.type==='ammoConsumed').map(e=>e.value),[1,0]);assert(own.some(e=>e.type==='fire'&&e.skillId===2001));}assert.equal(events[2].filter(e=>e.roomId===roomId).length,0);
 for(const c of clients.slice(0,2))assert((await c.callApi('Leave',{roomId,round:2})).isSucc);await Promise.all(clients.map(c=>c.disconnect()));await stop();await start();const restored=[];for(let i=0;i<2;i++){assert((await clients[i].connect()).isSucc);assert((await clients[i].callApi('Account',{token:accounts[i].token})).isSucc);const inventory=await clients[i].callApi('Inventory',{});assert(inventory.isSucc);assert.equal(inventory.res.records[0].ownedQuantity,0);assert.equal(inventory.res.hotkeys[0],77);restored.push(inventory.res);}evidence.actualRestart=restored;const reentry=await clients[0].callApi('CreateRoom',{mode:4,mapId:7,name:'恢复账户',tankId:1,roomName:'恢复库存验收'});assert(reentry.isSucc);assert((await clients[0].callApi('Ready',{round:1,isReady:true})).isSucc);await wait(()=>latest().roomId===reentry.res.room.id&&latest().phase==='PLAYING');const rebound=await clients[0].callApi('Inventory',{});assert(rebound.isSucc);assert.equal(rebound.res.records[0].battleQuantity,0);evidence.restartReentryInventory=rebound.res;assert((await clients[0].callApi('Leave',{roomId:reentry.res.room.id,round:1})).isSucc);evidence.status='PASS';console.log(JSON.stringify({status:'PASS',output,ownerFire:countFire(),consumed:[1,0],restartOwned:restored.map(i=>i.records[0].ownedQuantity)}));
 }catch(error){evidence.status='FAIL';evidence.error=String(error);throw error;}finally{evidence.snapshots=snapshots;evidence.events=events;await Promise.allSettled(clients.map(c=>c.disconnect()));await stop();writeFileSync(output+'.json',JSON.stringify(evidence,null,2)+'\n');writeFileSync(output+'.log',log);rmSync(dir,{recursive:true,force:true});}
}main().catch(e=>{console.error(e);process.exitCode=1;});
