import assert from 'node:assert/strict';
import {spawn,type ChildProcess} from 'node:child_process';
import {mkdtempSync,rmSync,writeFileSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {WsClient} from 'tsrpc';
import {serviceProto} from '../apps/shared/protocols/serviceProto';
import {AccountStore} from '../apps/server/src/account-store';
import type {MsgRoomSnapshot,MsgRoomEvent} from '../apps/shared/protocols';
async function main(){
 const runId=new Date().toISOString().replace(/[:.]/g,'-'),output='recovery/output/ammo11-consumption-network-'+runId,dir=mkdtempSync(join(tmpdir(),'cdtank-ammo11-consumption-')),database=join(dir,'accounts.sqlite'),port=3220;let server:ChildProcess|undefined,log='';
 const clients=Array.from({length:4},()=>new WsClient(serviceProto,{server:`ws://127.0.0.1:${port}`,logger:undefined,heartbeat:{interval:5000,timeout:10000}}));const snapshots:MsgRoomSnapshot[][]=clients.map(()=>[]),events:MsgRoomEvent[][]=clients.map(()=>[]);clients.forEach((c,i)=>{c.listenMsg('RoomSnapshot',s=>snapshots[i].push(s));c.listenMsg('RoomEvent',e=>events[i].push(e));});
 async function wait(f:()=>boolean,ms=10000){const end=Date.now()+ms;while(!f()&&Date.now()<end)await new Promise(r=>setTimeout(r,25));assert(f(),log.slice(-1000));}async function stop(){if(server?.exitCode===null&&server.signalCode===null){const end=new Promise<void>(r=>server!.once('exit',()=>r()));server.kill();await end;}}async function start(){const startOffset=log.length;server=spawn(process.execPath,['--import','tsx','apps/server/src/index.ts'],{env:{...process.env,PORT:String(port),ACCOUNT_DB_PATH:database,MATCH_TIME_LIMIT_SECONDS:'30'},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>{log+=String(d);});server.stderr!.on('data',d=>{log+=String(d);});await wait(()=>log.slice(startOffset).includes(`Server started at ${port}.`));}
 const latest=(i=0)=>snapshots[i].at(-1)!;const evidence:{[key:string]:unknown}={status:'RUNNING',runId,port,scope:'Rebuilt finite2011 owned/battle2; actual index normal accounts/Kitbag/room/Ready/PlayerInput; two natural30s CPU rounds, same-token second-room CAS rejection, actual restart and account isolation; no injected life/positions/events/results'};
 try{
 await start();const accounts=[];for(const c of clients.slice(0,3)){assert((await c.connect()).isSucc);const a=await c.callApi('Account',{});assert(a.isSucc);accounts.push(a.res);}
 const native=JSON.parse(readFileSync('recovery/output/world-role-attributes-native.json','utf8')).rows.find((r:{tankId:number;part:number})=>r.tankId===1&&r.part===0);const store=new AccountStore(database);try{for(const [index,owner] of accounts.slice(0,2).entries()){
 const fields=(v:Record<string,number>)=>new Map(Object.entries(v).map(([k,v])=>[Number(k),v]));const equipment={name:'明确导入原战车',fields:fields(native.equipment)},base={name:'明确导入原宠物',fields:fields(native.base)};equipment.fields.set(0x1c,72);equipment.fields.set(0x24,1);equipment.fields.set(0x28,index?10021:10011);equipment.fields.set(0x2c,index?10022:10012);equipment.fields.set(0x30,index?10023:10013);store.replaceRoleRecords(owner.accountId,{base:[base],equipment:[equipment]});store.replaceInventory(owner.accountId,[{instanceId:77,itemTableId:2011,ownedQuantity:2,battleQuantity:2,state:0,field8:0,float24Bits:0,float28Bits:0,float2cBits:0}]);const bytes=new Uint8Array(0x170),view=new DataView(bytes.buffer);view.setUint32(0xa8,72,true);view.setUint32(0xa4,base.fields.get(0)!,true);store.replaceRoleProfile(owner.accountId,{bytes,strings:['','']});}}finally{store.close();}
 for(const c of clients.slice(0,2))assert((await c.callApi('Kitbag',{operation:'ASSIGN',slot:1,instanceId:77})).isSucc);evidence.fixture={source:'world-role-attributes-native.json tank1/part0;browser-combat-muzzle-2011',instanceId:77,itemTableId:2011,ownedQuantity:2,battleQuantity:2,kitbagSlot:1,battleKey:2};
 const created=await clients[0].callApi('CreateRoom',{mode:4,mapId:7,name:'耗弹甲',tankId:1,roomName:'2011耗弹验收'});assert(created.isSucc);const roomId=created.res.room.id,ownerId=created.res.playerId;assert((await clients[1].callApi('Join',{roomId,clientId:'ignored',name:'耗弹乙',tankId:1})).isSucc);assert((await clients[0].callApi('Cpu',{round:1,operation:'ADD',tankId:1})).isSucc);
 assert((await clients[3].connect()).isSucc);assert((await clients[3].callApi('Account',{token:accounts[0].token})).isSucc);const twin=await clients[3].callApi('CreateRoom',{mode:4,mapId:7,name:'同账户另一房',tankId:1,roomName:'CAS验收'});assert(twin.isSucc,JSON.stringify(twin));assert((await clients[3].callApi('Ready',{round:1,isReady:true})).isSucc);await wait(()=>latest(3)?.phase==='PLAYING');
 const sequences=[0,0,0,0];async function input(i:number,fire=false,useItem=0){assert((await clients[i].sendMsg('PlayerInput',{sequence:++sequences[i],move:0,turn:0,aim:0,fire,useItem,clientTime:Date.now()})).isSucc);}await input(3,false,2);await wait(()=>latest(3).players.find(p=>p.id===twin.res.playerId)?.ammoItemId===2011);evidence.casLoaded=latest(3);
 for(const c of clients.slice(0,2))assert((await c.callApi('Ready',{round:1,isReady:true})).isSucc);await wait(()=>latest()?.phase==='PLAYING');evidence.initial=latest();await input(0,false,2);await wait(()=>latest().players.find(p=>p.id===ownerId)?.ammoItemId===2011);
 const owner=()=>latest().players.find(p=>p.id===ownerId)!,countFire=(id=ownerId,i=0)=>events[i].filter(e=>e.type==='fire'&&e.playerId===id).length;const persisted=()=>{const s=new AccountStore(database);try{return s.inventory(accounts[0].accountId);}finally{s.close();}};const consumption=[];
 for(let remaining=1;remaining>=0;remaining--){await wait(()=>owner().alive&&owner().reload.remaining===0);const before=countFire();await input(0,true);await wait(()=>countFire()===before+1);await input(0,false);const inventory=await clients[0].callApi('Inventory',{});assert(inventory.isSucc);assert.equal(inventory.res.records[0].ownedQuantity,remaining);assert.equal(inventory.res.records[0].battleQuantity,remaining);const durable=persisted();assert.equal(durable.records[0].ownedQuantity,remaining);assert.equal(owner().ammoItemId,2011);consumption.push({remaining,snapshot:latest(),inventory:inventory.res,persisted:durable});}evidence.consumption=consumption;
 await wait(()=>owner().alive&&owner().reload.remaining===0);const beforeRejected=countFire(),reloadBefore={...owner().reload};await input(0,true);await wait(()=>events[0].some(e=>e.type==='itemRejected'&&e.playerId===ownerId)&&owner().ammoItemId===2001);await input(0,false);assert.equal(countFire(),beforeRejected);assert.deepEqual(owner().reload,reloadBefore);evidence.emptyRejected={snapshot:latest(),reloadBefore,ownerFire:countFire()};
 const twinBefore=latest(3).players.find(p=>p.id===twin.res.playerId)!,twinReload={...twinBefore.reload};await input(3,true);await wait(()=>events[3].some(e=>e.type==='itemRejected'));await input(3,false);assert.equal(countFire(twin.res.playerId,3),0);const twinAfter=latest(3).players.find(p=>p.id===twin.res.playerId)!;assert.equal(twinAfter.ammoItemId,2011);assert.deepEqual(twinAfter.reload,twinReload);evidence.casRejected={before:twinBefore,after:twinAfter,events:events[3]};assert((await clients[3].callApi('Leave',{roomId:twin.res.room.id,round:1})).isSucc);
 const defaultBefore=countFire();await input(0,true);await wait(()=>countFire()===defaultBefore+1);await input(0,false);assert.equal(events[0].filter(e=>e.type==='fire'&&e.playerId===ownerId).at(-1)!.skillId,2001);assert.equal(persisted().records[0].ownedQuantity,0);evidence.defaultShot=latest();
 await wait(()=>latest().phase==='FINISHED',40000);evidence.finished=latest();assert(events[0].some(e=>e.type==='fire'&&e.playerId!==ownerId));assert(events[0].some(e=>e.type==='hit'));for(const c of clients.slice(0,2))assert((await c.callApi('Rematch',{round:1})).isSucc);await wait(()=>latest().phase==='PLAYING'&&latest().match?.round===2);evidence.rematch=latest();const inv2=await clients[0].callApi('Inventory',{});assert(inv2.isSucc);assert.equal(inv2.res.records[0].ownedQuantity,0);assert.equal(inv2.res.records[0].battleQuantity,0);evidence.round2Inventory=inv2.res;await wait(()=>latest().phase==='FINISHED'&&latest().match?.round===2,40000);evidence.round2Finished=latest();
 const sharedEvents=events[0].filter(e=>['ammoConsumed','fire','itemRejected'].includes(e.type)&&e.playerId===ownerId),peerEvents=events[1].filter(e=>['ammoConsumed','fire','itemRejected'].includes(e.type)&&e.playerId===ownerId);assert.deepEqual(sharedEvents,peerEvents);assert.deepEqual(sharedEvents.filter(e=>e.type==='ammoConsumed').map(e=>e.value),[1,0]);assert.equal(events[2].filter(e=>e.roomId===roomId).length,0);
 for(const c of clients.slice(0,2))assert((await c.callApi('Leave',{roomId,round:2})).isSucc);await Promise.all(clients.map(c=>c.disconnect()));await stop();await start();const restored=[];for(let i=0;i<2;i++){assert((await clients[i].connect()).isSucc);assert((await clients[i].callApi('Account',{token:accounts[i].token})).isSucc);const inventory=await clients[i].callApi('Inventory',{});assert(inventory.isSucc);assert.equal(inventory.res.records[0].ownedQuantity,i===0?0:2);assert.equal(inventory.res.hotkeys[0],77);restored.push(inventory.res);}evidence.actualRestart=restored;const reentry=await clients[0].callApi('CreateRoom',{mode:4,mapId:7,name:'恢复账户',tankId:1,roomName:'恢复库存验收'});assert(reentry.isSucc);assert((await clients[0].callApi('Ready',{round:1,isReady:true})).isSucc);await wait(()=>latest().roomId===reentry.res.room.id&&latest().phase==='PLAYING');const rebound=await clients[0].callApi('Inventory',{});assert(rebound.isSucc);assert.equal(rebound.res.records[0].battleQuantity,0);evidence.restartReentryInventory=rebound.res;assert((await clients[0].callApi('Leave',{roomId:reentry.res.room.id,round:1})).isSucc);evidence.status='PASS';console.log(JSON.stringify({status:'PASS',output,ownerFire:countFire(),consumed:[1,0],restartOwned:restored.map(i=>i.records[0].ownedQuantity)}));
 }catch(error){evidence.status='FAIL';evidence.error=String(error);throw error;}finally{evidence.snapshots=snapshots;evidence.events=events;await Promise.allSettled(clients.map(c=>c.disconnect()));await stop();writeFileSync(output+'.json',JSON.stringify(evidence,null,2)+'\n');writeFileSync(output+'.log',log);rmSync(dir,{recursive:true,force:true});}
}main().catch(e=>{console.error(e);process.exitCode=1;});
