import assert from 'node:assert/strict';
import {spawn,type ChildProcess} from 'node:child_process';
import {mkdtempSync,rmSync,writeFileSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {WsClient} from 'tsrpc';
import {serviceProto} from '../apps/shared/protocols/serviceProto';
import {AccountStore} from '../apps/server/src/account-store';
import type {MsgRoomSnapshot,MsgRoomEvent} from '../apps/shared/protocols';
async function main(){
 const runId=new Date().toISOString().replace(/[:.]/g,'-'),output='recovery/output/ammo07-purchase-network-'+runId,dir=mkdtempSync(join(tmpdir(),'cdtank-ammo07-purchase-')),database=join(dir,'accounts.sqlite'),port=3229;let server:ChildProcess|undefined,log='';
 const clients=Array.from({length:4},()=>new WsClient(serviceProto,{server:`ws://127.0.0.1:${port}`,logger:undefined,heartbeat:{interval:5000,timeout:10000}}));const snapshots:MsgRoomSnapshot[][]=clients.map(()=>[]),events:MsgRoomEvent[][]=clients.map(()=>[]),timed:{page:number;tick:number;receivedAt:number;event:MsgRoomEvent}[]=[];clients.forEach((c,i)=>{c.listenMsg('RoomSnapshot',s=>{snapshots[i].push(s);});c.listenMsg('RoomEvent',e=>{events[i].push(e);timed.push({page:i,tick:snapshots[i].at(-1)?.tick??0,receivedAt:Date.now(),event:e});});});
 async function wait(f:()=>boolean,ms=10000){const end=Date.now()+ms;while(!f()&&Date.now()<end)await new Promise(r=>setTimeout(r,25));assert(f(),log.slice(-1000));}async function stop(){if(server?.exitCode===null&&server.signalCode===null){const end=new Promise<void>(r=>server!.once('exit',()=>r()));server.kill();await end;}}async function start(){const startOffset=log.length;server=spawn(process.execPath,['--import','tsx','apps/server/src/index.ts'],{env:{...process.env,PORT:String(port),ACCOUNT_DB_PATH:database,MATCH_TIME_LIMIT_SECONDS:'30'},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>{log+=String(d);});server.stderr!.on('data',d=>{log+=String(d);});await wait(()=>log.slice(startOffset).includes(`Server started at ${port}.`));}
 const latest=(i=0)=>snapshots[i].at(-1)!;const evidence:{[key:string]:unknown}={status:'RUNNING',runId,port,scope:'Rebuilt paid2007 actual BUY instance at source MONEY10/TOKENS20, empty inventory and experimental native-profile funds, Home-equivalent Kitbag/normal AI fire then stop, natural4005 three70HP ticks, two rounds and sameDB original-token restart'};
 try{
 await start();const accounts:{accountId:string;token:string}[]=[];for(const c of clients.slice(0,3)){assert((await c.connect()).isSucc);const a=await c.callApi('Account',{});assert(a.isSucc);accounts.push(a.res);}
 const template=JSON.parse(readFileSync('recovery/output/world-role-attributes-native.json','utf8')).rows.find((r:{tankId:number;part:number})=>r.tankId===1&&r.part===0);const store=new AccountStore(database);
 const base=new Map<number,number>(Object.keys(template.base).map(k=>[Number(k),0])),equipment=new Map<number,number>(Object.keys(template.equipment).map(k=>[Number(k),0]));base.set(0,73);base.set(8,1);base.set(0x2c,600);base.set(0x34,5);base.set(0x3c,10);equipment.set(0x1c,74);equipment.set(0x24,1);equipment.set(0x3c,100);equipment.set(0x40,70);equipment.set(0x4c,15);equipment.set(0x50,30);equipment.set(0x58,2001);
 try{for(const [i,account]of accounts.entries()){store.replaceRoleRecords(account.accountId,{base:[{name:'Explicit base pet1 fixture',fields:base}],equipment:[{name:'Explicit base tank1 fixture',fields:equipment}]});assert.equal(store.inventory(account.accountId).records.length,0);const bytes=new Uint8Array(0x170),view=new DataView(bytes.buffer);view.setUint32(0xa4,73,true);view.setUint32(0xa8,74,true);view.setUint32(0x70,i===0?200:i===1?5:0,true);view.setUint32(0x74,i===2?40:0,true);store.replaceRoleProfile(account.accountId,{bytes,strings:['','']});}}finally{store.close();}
 const query=await clients[0].callApi('Shop',{operation:'QUERY'});assert(query.isSucc);const product=query.res.items.find(i=>i.itemTableId===2007)!;assert.equal(product.moneyPrice,10);assert.equal(product.tokenPrice,20);const request={operation:'BUY' as const,itemTableId:2007,quantity:1,currency:'MONEY' as const,requestId:'ammo07_money_0001'};const paid=await clients[0].callApi('Shop',request);assert(paid.isSucc);assert.equal(paid.res.money,190);assert.equal(paid.res.purchased!.ownedQuantity,1);const instanceId=paid.res.purchased!.instanceId;evidence.purchase=paid.res;const shortage=await clients[1].callApi('Shop',{...request,requestId:'ammo07_shortage_0001'});assert(!shortage.isSucc);const empty=await clients[1].callApi('Inventory',{});assert(empty.isSucc&&empty.res.records.length===0);const shortBalance=await clients[1].callApi('Shop',{operation:'QUERY'});assert(shortBalance.isSucc&&shortBalance.res.money===5&&shortBalance.res.tokens===0);evidence.insufficient={shortage,inventory:empty.res,balance:shortBalance.res};const tokenBuy=await clients[2].callApi('Shop',{...request,currency:'TOKENS',requestId:'ammo07_tokens_0001'});assert(tokenBuy.isSucc);assert.equal(tokenBuy.res.tokens,20);assert.equal(tokenBuy.res.money,0);assert.equal(tokenBuy.res.purchased!.ownedQuantity,1);evidence.tokensPurchase=tokenBuy.res;
 evidence.fixture={source:'tank-numeric-sol-network measured pet1HP600 fixture; world-role-attributes-native complete field layout',base:[...base],equipment:[...equipment],initialInventory:'empty',experimentalMoney:[200,5,0],experimentalTokens:[0,0,40],instanceId};assert((await clients[0].callApi('Kitbag',{operation:'ASSIGN',slot:1,instanceId})).isSucc);
 const created=await clients[0].callApi('CreateRoom',{mode:4,mapId:7,name:'燃烧发射者',tankId:1,roomName:'2007持续伤害'});assert(created.isSucc);const roomId=created.res.room.id,ownerId=created.res.playerId;const joined=await clients[1].callApi('Join',{roomId,clientId:'ignored',name:'燃烧目标',tankId:1});assert(joined.isSucc);const targetId=joined.res.playerId;
 assert((await clients[0].callApi('Autopilot',{round:1,enabled:true})).isSucc);for(const c of clients.slice(0,2))assert((await c.callApi('Ready',{round:1,isReady:true})).isSucc);await wait(()=>latest()?.phase==='PLAYING');evidence.initial=latest();assert(latest().players.every(p=>p.maxHp===(600)));
 await wait(()=>events[0].filter(e=>e.type==='fire'&&e.playerId===ownerId&&e.skillId===2007).length===(1),20000);assert((await clients[0].callApi('Autopilot',{round:1,enabled:false})).isSucc);assert((await clients[0].sendMsg('PlayerInput',{sequence:1,move:0,turn:0,aim:0,fire:false,useItem:0,clientTime:Date.now()})).isSucc);evidence.stopAfterNatural2007=latest();
 await wait(()=>events[0].some(e=>e.type==='hit'&&e.playerId===ownerId&&e.targetId===targetId),10000);const initialHit=timed.find(r=>r.page===0&&r.event.type==='hit'&&r.event.playerId===ownerId&&r.event.targetId===targetId)!;evidence.initialHit=initialHit; await wait(()=>events[0].filter(e=>e.type==='hit'&&e.skillId===4005).length===3,15000);const periodic=timed.filter(r=>r.page===0&&r.event.type==='hit'&&r.event.skillId===4005);evidence.periodic=periodic;assert.deepEqual(periodic.map(r=>r.event.value),[70,70,70]);assert(periodic.every(r=>r.event.playerId===ownerId&&r.event.targetId===targetId&&r.event.hurtSelector===undefined));for(const [i,r]of periodic.entries())assert(Math.abs(r.tick-initialHit.tick-(i+1)*60)<=3,'Expected 3/6/9 second burn cadence');
 await wait(()=>latest().tick>=periodic[2].tick+65,6000);assert.equal(events[0].filter(e=>e.type==='hit'&&e.skillId===4005).length,3);const hits=events[0].filter(e=>e.type==='hit'&&e.targetId===targetId);assert.equal(latest().players.find(p=>p.id===targetId)!.hp,600-hits.reduce((total,e)=>total+e.value,0));evidence.expired=latest();evidence.damageAccounting={initialHealth:600,hits,finalHealth:latest().players.find(p=>p.id===targetId)!.hp};
 await wait(()=>latest().phase==='FINISHED',40000);evidence.finished=latest();for(const c of clients.slice(0,2))assert((await c.callApi('Rematch',{round:1})).isSucc);await wait(()=>latest().phase==='PLAYING'&&latest().match?.round===2);evidence.rematch=latest();assert(latest().players.every(p=>p.hp===600));assert.equal(latest().players.find(p=>p.id===ownerId)!.ammoSlots![0].quantity,0);await wait(()=>latest().phase==='FINISHED'&&latest().match?.round===2,40000);evidence.round2Finished=latest();assert.equal(events[0].filter(e=>e.type==='hit'&&e.skillId===4005).length,3);const shared=(i:number)=>events[i].filter(e=>['fire','hit','ammoConsumed','finish'].includes(e.type));assert.deepEqual(shared(0),shared(1));evidence.sharedEvents=shared(0);for(const c of clients.slice(0,2))assert((await c.callApi('Leave',{roomId,round:2})).isSucc);const inv=await clients[0].callApi('Inventory',{});assert(inv.isSucc);assert.equal(inv.res.records.find(r=>r.instanceId===instanceId)!.ownedQuantity,0);assert.equal(inv.res.hotkeys[0],instanceId);await Promise.all(clients.map(c=>c.disconnect()));await stop();await start();evidence.actualRestart=[];const restored=[];for(let i=0;i<3;i++){assert((await clients[i].connect()).isSucc);assert((await clients[i].callApi('Account',{token:accounts[i].token})).isSucc);const inventory=await clients[i].callApi('Inventory',{});assert(inventory.isSucc);const balance=await clients[i].callApi('Shop',{operation:'QUERY'});assert(balance.isSucc);assert.equal(balance.res.money,[190,5,0][i]);assert.equal(balance.res.tokens,[0,0,20][i]);if(i===0){assert.equal(inventory.res.records[0].instanceId,instanceId);assert.equal(inventory.res.records[0].ownedQuantity,0);assert.equal(inventory.res.hotkeys[0],instanceId);}else if(i===1)assert.equal(inventory.res.records.length,0);else assert.equal(inventory.res.records[0].ownedQuantity,1);restored.push({inventory:inventory.res,money:balance.res.money,tokens:balance.res.tokens});}evidence.actualRestart=restored;evidence.status='PASS';console.log(JSON.stringify({status:'PASS',output,periodicTicks:periodic.map(r=>r.tick),finalHp:(evidence.expired as MsgRoomSnapshot).players.find(p=>p.id===targetId)!.hp}));
 }catch(error){evidence.status='FAIL';evidence.error=String(error);throw error;}finally{evidence.snapshots=snapshots;evidence.events=events;evidence.timed=timed;await Promise.allSettled(clients.map(c=>c.disconnect()));await stop();writeFileSync(output+'.json',JSON.stringify(evidence,null,2)+'\n');writeFileSync(output+'.log',log);rmSync(dir,{recursive:true,force:true});}
}main().catch(e=>{console.error(e);process.exitCode=1;});
