import assert from 'node:assert/strict';
import {spawn,type ChildProcess} from 'node:child_process';
import {mkdtempSync,rmSync,writeFileSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {WsClient} from 'tsrpc';
import {serviceProto} from '../apps/shared/protocols/serviceProto';
import {AccountStore} from '../apps/server/src/account-store';
import type {MsgRoomSnapshot,MsgRoomEvent} from '../apps/shared/protocols';
async function main(){
 
 const runId=new Date().toISOString().replace(/[:.]/g,'-'),output='recovery/output/cpu-loadout-network-'+runId,dir=mkdtempSync(join(tmpdir(),'cdtank-cpu-loadout-')),database=join(dir,'accounts.sqlite'),port=3237;let server:ChildProcess|undefined,log='';
 const clients=Array.from({length:4},()=>new WsClient(serviceProto,{server:`ws://127.0.0.1:${port}`,logger:undefined,heartbeat:{interval:5000,timeout:10000}}));const snapshots:MsgRoomSnapshot[][]=clients.map(()=>[]),events:MsgRoomEvent[][]=clients.map(()=>[]),timed:{page:number;tick:number;receivedAt:number;event:MsgRoomEvent}[]=[];clients.forEach((c,i)=>{c.listenMsg('RoomSnapshot',s=>{snapshots[i].push(s);});c.listenMsg('RoomEvent',e=>{events[i].push(e);timed.push({page:i,tick:snapshots[i].at(-1)?.tick??0,receivedAt:Date.now(),event:e});});});
 async function wait(f:()=>boolean,ms=10000){const end=Date.now()+ms;while(!f()&&Date.now()<end)await new Promise(r=>setTimeout(r,25));assert(f(),log.slice(-1000));}async function stop(){if(server?.exitCode===null&&server.signalCode===null){const end=new Promise<void>(r=>server!.once('exit',()=>r()));server.kill();await end;}}async function start(){const startOffset=log.length;server=spawn(process.execPath,['--import','tsx','apps/server/src/index.ts'],{env:{...process.env,PORT:String(port),ACCOUNT_DB_PATH:database,MATCH_TIME_LIMIT_SECONDS:'30'},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>{log+=String(d);});server.stderr!.on('data',d=>{log+=String(d);});await wait(()=>log.slice(startOffset).includes(`Server started at ${port}.`));}
 const latest=(i=0)=>snapshots[i].at(-1)!;const evidence:{[key:string]:unknown}={status:'RUNNING',runId,port,scope:'Rebuilt authenticated WAITING CpuCONFIGURE temporary finite2007/item3, natural CPU fire/hit/selfcleanse, rejection atomicity, actual human item2 durableCAS, account isolation, two natural rounds/remaining stock and sameDB restart'};
 try{
 await start();const accounts:{accountId:string;token:string}[]=[];for(const c of clients.slice(0,3)){assert((await c.connect()).isSucc);const a=await c.callApi('Account',{});assert(a.isSucc);accounts.push(a.res);}
 const template=JSON.parse(readFileSync('recovery/output/world-role-attributes-native.json','utf8')).rows.find((r:{tankId:number;part:number})=>r.tankId===1&&r.part===0);const store=new AccountStore(database);
 const base=new Map<number,number>(Object.keys(template.base).map(k=>[Number(k),0])),equipment=new Map<number,number>(Object.keys(template.equipment).map(k=>[Number(k),0]));base.set(0,73);base.set(8,1);base.set(0x2c,600);base.set(0x34,5);base.set(0x3c,10);equipment.set(0x1c,74);equipment.set(0x24,1);equipment.set(0x3c,100);equipment.set(0x40,70);equipment.set(0x4c,15);equipment.set(0x50,30);equipment.set(0x58,2001);
 try{for(const [i,account]of accounts.slice(0,2).entries()){store.replaceRoleRecords(account.accountId,{base:[{name:'Explicit base pet1 fixture',fields:base}],equipment:[{name:'Explicit base tank1 fixture',fields:equipment}]});store.replaceInventory(account.accountId,[{instanceId:78,itemTableId:2,ownedQuantity:2,battleQuantity:2,state:0,field8:0,float24Bits:0,float28Bits:0,float2cBits:0}]);const bytes=new Uint8Array(0x170),view=new DataView(bytes.buffer);view.setUint32(0xa4,73,true);view.setUint32(0xa8,74,true);view.setUint32(0x70,100,true);view.setUint32(0x74,40,true);store.replaceRoleProfile(account.accountId,{bytes,strings:['','']});}}finally{store.close();}
 evidence.fixture={source:'explicit measured sourceHP600/tank1 fixture',base:[...base],equipment:[...equipment],humanHeldItem2:2,balances:{money:100,tokens:40}};for(const c of clients.slice(0,2))assert((await c.callApi('Kitbag',{operation:'ASSIGN',slot:4,instanceId:78})).isSucc);
 const created=await clients[0].callApi('CreateRoom',{mode:4,mapId:7,name:'燃烧发射者',tankId:1,roomName:'2007持续伤害'});assert(created.isSucc);const roomId=created.res.room.id,ownerId=created.res.playerId;const joined=await clients[1].callApi('Join',{roomId,clientId:'ignored',name:'燃烧目标',tankId:1});assert(joined.isSucc);const targetId=joined.res.playerId;
 const loadout=[{slot:2,itemTableId:2007,quantity:2},{slot:5,itemTableId:3,quantity:2}],cpuIds:string[]=[];for(let i=0;i<3;i++){const add=await clients[0].callApi('Cpu',{round:1,operation:'ADD',tankId:1});assert(add.isSucc);cpuIds.push(add.res.playerId);assert((await clients[0].callApi('Cpu',{round:1,operation:'CONFIGURE',playerId:add.res.playerId,loadout})).isSucc);}await wait(()=>latest()?.players.filter(p=>p.isCpu&&p.cpuLoadout?.length===2).length===3);const before=latest();const reject=await clients[1].callApi('Cpu',{round:1,operation:'CONFIGURE',playerId:cpuIds[0],loadout});assert(!reject.isSucc);const malformed=await clients[0].callApi('Cpu',{round:1,operation:'CONFIGURE',playerId:cpuIds[0],loadout:[...loadout,{slot:5,itemTableId:3,quantity:1}]});assert(!malformed.isSucc);const stale=await clients[0].callApi('Cpu',{round:2,operation:'CONFIGURE',playerId:cpuIds[0],loadout});assert(!stale.isSucc);await new Promise(r=>setTimeout(r,100));assert.deepEqual(latest().players.filter(p=>p.isCpu).map(p=>p.cpuLoadout),before.players.filter(p=>p.isCpu).map(p=>p.cpuLoadout));assert.deepEqual(latest().match?.readyPlayerIds,before.match?.readyPlayerIds);evidence.rejectionState={before,after:latest()};evidence.rejections={nonHost:reject,malformed,stale};evidence.configured=latest();
 const initialAccounts=[];for(const c of clients.slice(0,2)){const inventory=await c.callApi('Inventory',{});assert(inventory.isSucc);assert.equal(inventory.res.records[0].ownedQuantity,2);assert.equal(inventory.res.hotkeys[3],78);const balance=await c.callApi('Shop',{operation:'QUERY'});assert(balance.isSucc&&balance.res.money===100&&balance.res.tokens===40);initialAccounts.push({inventory:inventory.res,money:balance.res.money,tokens:balance.res.tokens});}evidence.accountBefore=initialAccounts;
 for(const c of clients.slice(0,2))assert((await c.callApi('Ready',{round:1,isReady:true})).isSucc);await wait(()=>latest()?.phase==='PLAYING');evidence.initial=latest();const gate=await clients[0].callApi('Cpu',{round:1,operation:'CONFIGURE',playerId:cpuIds[0],loadout});assert(!gate.isSucc);evidence.playingReject=gate;
 await wait(()=>events[0].some(e=>e.type==='itemUsed'&&e.skillId===3&&cpuIds.includes(e.playerId)),25000);const used=timed.find(r=>r.page===0&&r.event.type==='itemUsed'&&r.event.skillId===3&&cpuIds.includes(r.event.playerId))!;const prior=timed.filter(r=>r.page===0&&r.event.type==='hit'&&r.event.targetId===used.event.playerId&&r.tick<=used.tick).at(-1)!;assert(prior);assert(events[0].some(e=>e.type==='fire'&&e.skillId===2007&&e.playerId===prior.event.playerId));const beforeUse=snapshots[0].filter(s=>s.tick<=used.tick).at(-1);evidence.cpuCausal={hit:prior,used,beforeUse};await wait(()=>latest().players.find(p=>p.id===used.event.playerId)?.cpuLoadout?.find(i=>i.itemTableId===3)?.quantity===1);evidence.afterCPUUse=latest();
 await wait(()=>latest().players.some(p=>!p.isCpu&&p.hp<p.maxHp&&p.alive),10000);const injured=latest().players.find(p=>!p.isCpu&&p.hp<p.maxHp&&p.alive)!;const healClient=injured.id===ownerId?0:1;assert((await clients[healClient].sendMsg('PlayerInput',{sequence:1,move:0,turn:0,aim:0,fire:false,useItem:5,clientTime:Date.now()})).isSucc);await wait(()=>events[0].some(e=>e.type==='itemUsed'&&e.skillId===2&&e.playerId===injured.id));evidence.humanUsed=events[0].find(e=>e.type==='itemUsed'&&e.skillId===2&&e.playerId===injured.id);const healing=await clients[healClient].callApi('Inventory',{});assert(healing.isSucc&&healing.res.records[0].ownedQuantity===1);const persisted=new AccountStore(database);try{assert.equal(persisted.inventory(accounts[healClient].accountId).records[0].ownedQuantity,1);}finally{persisted.close();}evidence.humanCAS={accountIndex:healClient,inventory:healing.res};
 await wait(()=>latest().phase==='FINISHED',40000);evidence.finished=latest();for(const c of clients.slice(0,2))assert((await c.callApi('Rematch',{round:1})).isSucc);await wait(()=>latest().phase==='PLAYING'&&latest().match?.round===2);evidence.rematch=latest();const remaining=evidence.finished as MsgRoomSnapshot;assert.deepEqual(latest().players.filter(p=>p.isCpu).map(p=>p.cpuLoadout),remaining.players.filter(p=>p.isCpu).map(p=>p.cpuLoadout));await wait(()=>latest().phase==='FINISHED'&&latest().match?.round===2,40000);evidence.round2Finished=latest();const shared=(i:number)=>events[i].filter(e=>['fire','hit','ammoConsumed','itemUsed','itemRejected','finish'].includes(e.type));assert.deepEqual(shared(0),shared(1));evidence.sharedEvents=shared(0);for(const c of clients.slice(0,2))assert((await c.callApi('Leave',{roomId,round:2})).isSucc);await Promise.all(clients.map(c=>c.disconnect()));await stop();await start();const restored=[];for(let i=0;i<2;i++){assert((await clients[i].connect()).isSucc);assert((await clients[i].callApi('Account',{token:accounts[i].token})).isSucc);const inventory=await clients[i].callApi('Inventory',{});assert(inventory.isSucc);assert.equal(inventory.res.records[0].ownedQuantity,i===healClient?1:2);assert.equal(inventory.res.hotkeys[3],78);const balance=await clients[i].callApi('Shop',{operation:'QUERY'});assert(balance.isSucc&&balance.res.money===100&&balance.res.tokens===40);restored.push({inventory:inventory.res,money:balance.res.money,tokens:balance.res.tokens});}evidence.actualRestart=restored;const newRoom=await clients[0].callApi('CreateRoom',{mode:4,mapId:7,name:'恢复账户',tankId:1,roomName:'CPU临时量清理'});assert(newRoom.isSucc);const add=await clients[0].callApi('Cpu',{round:1,operation:'ADD',tankId:1});assert(add.isSucc);await wait(()=>latest().roomId===newRoom.res.room.id&&latest().players.some(p=>p.id===add.res.playerId));assert.equal(latest().players.find(p=>p.id===add.res.playerId)!.cpuLoadout?.length??0,0);assert((await clients[0].callApi('Cpu',{round:1,operation:'REMOVE',playerId:add.res.playerId})).isSucc);await wait(()=>!latest().players.some(p=>p.id===add.res.playerId));evidence.removal=latest();assert((await clients[0].callApi('Leave',{roomId:newRoom.res.room.id,round:1})).isSucc);evidence.status='PASS';console.log(JSON.stringify({status:'PASS',output,cpuUsed:used.event.playerId,humanCAS:healClient}));
 }catch(error){evidence.status='FAIL';evidence.error=String(error);throw error;}finally{evidence.snapshots=snapshots;evidence.events=events;evidence.timed=timed;await Promise.allSettled(clients.map(c=>c.disconnect()));await stop();writeFileSync(output+'.json',JSON.stringify(evidence,null,2)+'\n');writeFileSync(output+'.log',log);rmSync(dir,{recursive:true,force:true});}
}main().catch(e=>{console.error(e);process.exitCode=1;});
