import assert from 'node:assert/strict';
import {spawn,type ChildProcess} from 'node:child_process';
import {mkdtempSync,rmSync,writeFileSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {WsClient} from 'tsrpc';
import {serviceProto} from '../apps/shared/protocols/serviceProto';
import {AccountStore} from '../apps/server/src/account-store';
import type {MsgRoomSnapshot,MsgRoomEvent} from '../apps/shared/protocols';
async function main(){
 
 const runId=new Date().toISOString().replace(/[:.]/g,'-'),output='recovery/output/ordinary2001-immediate-network-'+runId,dir=mkdtempSync(join(tmpdir(),'cdtank-ordinary2001-immediate-')),database=join(dir,'accounts.sqlite'),port=3249;let server:ChildProcess|undefined,log='';
 const clients=Array.from({length:2},()=>new WsClient(serviceProto,{server:`ws://127.0.0.1:${port}`,logger:undefined,heartbeat:{interval:5000,timeout:10000}}));const snapshots:MsgRoomSnapshot[][]=clients.map(()=>[]),events:MsgRoomEvent[][]=clients.map(()=>[]),timed:{page:number;tick:number;receivedAt:number;event:MsgRoomEvent}[]=[];clients.forEach((c,i)=>{c.listenMsg('RoomSnapshot',s=>{snapshots[i].push(s);});c.listenMsg('RoomEvent',e=>{events[i].push(e);timed.push({page:i,tick:snapshots[i].at(-1)?.tick??0,receivedAt:Date.now(),event:e});});});
 async function wait(f:()=>boolean,ms=10000){const end=Date.now()+ms;while(!f()&&Date.now()<end)await new Promise(r=>setTimeout(r,25));assert(f(),log.slice(-1000));}async function stop(){if(server?.exitCode===null&&server.signalCode===null){const end=new Promise<void>(r=>server!.once('exit',()=>r()));server.kill();await end;}}async function start(){const startOffset=log.length;server=spawn(process.execPath,['--import','tsx','apps/server/src/index.ts'],{env:{...process.env,PORT:String(port),ACCOUNT_DB_PATH:database,MATCH_TIME_LIMIT_SECONDS:'90'},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>{log+=String(d);});server.stderr!.on('data',d=>{log+=String(d);});await wait(()=>log.slice(startOffset).includes(`Server started at ${port}.`));}
 const latest=(i=0)=>snapshots[i].at(-1)!;const evidence:{[key:string]:unknown}={status:'RUNNING',runId,port,scope:'Two authenticated normal map7/mode4 accounts HP200 plus CPU default2001; immediate same-tick fire-hit source metadata/order/sharedHP, no bullets, FREE/SCENE no false player results, normal death/respawn/Leave; no state injection/restart/secondround'};
 try{
 await start();const accounts:{accountId:string;token:string}[]=[];for(const c of clients){assert((await c.connect()).isSucc);const a=await c.callApi('Account',{});assert(a.isSucc);accounts.push(a.res);}
 const template=JSON.parse(readFileSync('recovery/output/world-role-attributes-native.json','utf8')).rows.find((r:{tankId:number;part:number})=>r.tankId===1&&r.part===0);const store=new AccountStore(database),base=new Map<number,number>(Object.keys(template.base).map(k=>[Number(k),0])),equipment=new Map<number,number>(Object.keys(template.equipment).map(k=>[Number(k),0]));base.set(0,73);base.set(8,1);base.set(0x2c,200);base.set(0x34,5);base.set(0x3c,10);equipment.set(0x1c,74);equipment.set(0x24,1);equipment.set(0x3c,100);equipment.set(0x40,70);equipment.set(0x4c,15);equipment.set(0x50,30);equipment.set(0x58,2001);try{for(const account of accounts){store.replaceRoleRecords(account.accountId,{base:[{name:'Explicit HP200 pet1 fixture',fields:base}],equipment:[{name:'Explicit tank1 default2001 fixture',fields:equipment}]});assert.equal(store.inventory(account.accountId).records.length,0);const bytes=new Uint8Array(0x170),v=new DataView(bytes.buffer);v.setUint32(0xa4,73,true);v.setUint32(0xa8,74,true);store.replaceRoleProfile(account.accountId,{bytes,strings:['','']});}}finally{store.close();}evidence.fixture={base:[...base],equipment:[...equipment],noSpecialInventory:true};
 const created=await clients[0].callApi('CreateRoom',{mode:4,mapId:7,name:'普通即时',tankId:1,roomName:'普通即时'});assert(created.isSucc);const roomId=created.res.room.id,ownerId=created.res.playerId;const joined=await clients[1].callApi('Join',{clientId:'ordinary-peer',name:'即时观察',tankId:1,roomId});assert(joined.isSucc);assert((await clients[0].callApi('Cpu',{round:1,operation:'ADD',tankId:1})).isSucc);assert((await clients[1].callApi('Ready',{round:1,isReady:true})).isSucc);assert((await clients[0].callApi('Ready',{round:1,isReady:true})).isSucc);await wait(()=>latest()?.phase==='PLAYING');evidence.initial=latest();assert.equal(latest().players.find(p=>p.id===ownerId)!.maxHp,200);
 // One ordinary initial shot follows the unmodified spawn aim; no target/position injection.
 assert((await clients[0].sendMsg('PlayerInput',{sequence:1,move:0,turn:0,aim:0,fire:true,useItem:0,clientTime:Date.now()})).isSucc);await wait(()=>events[0].some(e=>e.type==='fire'&&e.playerId===ownerId));assert((await clients[0].sendMsg('PlayerInput',{sequence:2,move:0,turn:0,aim:0,fire:false,useItem:0,clientTime:Date.now()})).isSucc);assert((await clients[0].callApi('Autopilot',{round:1,enabled:true})).isSucc);assert((await clients[1].callApi('Autopilot',{round:1,enabled:true})).isSucc);
 await wait(()=>events[0].some(e=>e.type==='hit'&&e.shotPlayerResult?.itemId===2001)&&events[0].some(e=>e.type==='destroy')&&events[0].some(e=>e.type==='respawn'),60000);
 await wait(()=>events[1].length>=events[0].length-5);const relevant=(i:number)=>timed.filter(t=>t.page===i&&['fire','hit','terrainHit','objectHit','objectDestroyed','destroy','respawn'].includes(t.event.type));const firstHit=relevant(0).find(t=>t.event.type==='hit'&&t.event.shotPlayerResult?.itemId===2001)!;const hitIndex=events[0].indexOf(firstHit.event),fire=events[0].slice(0,hitIndex).reverse().find(e=>e.type==='fire'&&e.playerId===firstHit.event.playerId&&e.targetId===firstHit.event.targetId)!;assert(fire&&fire.skillId===2001&&!fire.shotDisplay);const fireTimed=timed.find(t=>t.page===0&&t.event===fire)!;assert.equal(fireTimed.tick,firstHit.tick);const peerHit=relevant(1).find(t=>JSON.stringify(t.event)===JSON.stringify(firstHit.event))!;assert(peerHit);const peerFire=relevant(1).find(t=>JSON.stringify(t.event)===JSON.stringify(fire))!;assert(peerFire);assert.equal(peerFire.tick,peerHit.tick);assert(relevant(1).indexOf(peerFire)<relevant(1).indexOf(peerHit));evidence.immediate={fire:fireTimed,hit:firstHit,peerFire,peerHit};
 const left=relevant(0).map(t=>t.event),right=relevant(1).map(t=>t.event),sharedCount=Math.min(left.length,right.length);assert.deepEqual(left.slice(0,sharedCount),right.slice(0,sharedCount));evidence.orderedNotices={sharedCount,events:left.slice(0,sharedCount)};assert(snapshots.every(s=>s.every(w=>w.bullets.length===0)));evidence.noBullets=true;
 const display=relevant(0).filter(t=>t.event.type==='fire'&&t.event.shotDisplay?.itemId===2001);assert(display.length>0);for(const shot of display){assert(!shot.event.shotPlayerResult);assert(!relevant(0).some(t=>t.tick===shot.tick&&t.event.type==='hit'&&t.event.playerId===shot.event.playerId&&t.event.targetId===shot.event.targetId&&t.event.shotPlayerResult));}evidence.sceneFreeDisplays=display;
 const matching=snapshots[0].find(a=>a.tick>firstHit.tick&&a.players.some(p=>p.id===firstHit.event.targetId&&p.hp<p.maxHp)&&snapshots[1].some(b=>a.tick===b.tick&&JSON.stringify(a.players)===JSON.stringify(b.players)));assert(matching);evidence.sharedSnapshot={owner:matching,peer:snapshots[1].find(b=>b.tick===matching.tick)};evidence.life={destroy:events[0].find(e=>e.type==='destroy'),respawn:events[0].find(e=>e.type==='respawn')};for(const c of clients)assert((await c.callApi('Leave',{roomId,round:1})).isSucc);evidence.leave=true;evidence.status='PASS';console.log(JSON.stringify({status:'PASS',output,immediateTick:firstHit.tick,sharedCount}));
 }catch(error){evidence.status='FAIL';evidence.error=String(error);throw error;}finally{evidence.snapshots=snapshots;evidence.events=events;evidence.timed=timed;await Promise.allSettled(clients.map(c=>c.disconnect()));await stop();writeFileSync(output+'.json',JSON.stringify(evidence,null,2)+'\n');writeFileSync(output+'.log',log);rmSync(dir,{recursive:true,force:true});}
}main().catch(e=>{console.error(e);process.exitCode=1;});
