import assert from 'node:assert/strict';
import {spawn,type ChildProcess} from 'node:child_process';
import {mkdtempSync,rmSync,writeFileSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {WsClient} from 'tsrpc';
import {serviceProto} from '../apps/shared/protocols/serviceProto';
import {AccountStore} from '../apps/server/src/account-store';
import type {MsgRoomSnapshot,MsgRoomEvent} from '../apps/shared/protocols';
async function main(){
 
 const runId=new Date().toISOString().replace(/[:.]/g,'-'),output='recovery/output/pet-injection-network-'+runId,dir=mkdtempSync(join(tmpdir(),'cdtank-pet-injection-')),database=join(dir,'accounts.sqlite'),port=3231;let server:ChildProcess|undefined,log='';
 const clients=Array.from({length:4},()=>new WsClient(serviceProto,{server:`ws://127.0.0.1:${port}`,logger:undefined,heartbeat:{interval:5000,timeout:10000}}));const snapshots:MsgRoomSnapshot[][]=clients.map(()=>[]),events:MsgRoomEvent[][]=clients.map(()=>[]),timed:{page:number;tick:number;receivedAt:number;event:MsgRoomEvent}[]=[];clients.forEach((c,i)=>{c.listenMsg('RoomSnapshot',s=>{snapshots[i].push(s);});c.listenMsg('RoomEvent',e=>{events[i].push(e);timed.push({page:i,tick:snapshots[i].at(-1)?.tick??0,receivedAt:Date.now(),event:e});});});
 async function wait(f:()=>boolean,ms=10000){const end=Date.now()+ms;while(!f()&&Date.now()<end)await new Promise(r=>setTimeout(r,25));assert(f(),log.slice(-1000));}async function stop(){if(server?.exitCode===null&&server.signalCode===null){const end=new Promise<void>(r=>server!.once('exit',()=>r()));server.kill();await end;}}async function start(){const startOffset=log.length;server=spawn(process.execPath,['--import','tsx','apps/server/src/index.ts'],{env:{...process.env,PORT:String(port),ACCOUNT_DB_PATH:database,MATCH_TIME_LIMIT_SECONDS:'30'},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>{log+=String(d);});server.stderr!.on('data',d=>{log+=String(d);});await wait(()=>log.slice(startOffset).includes(`Server started at ${port}.`));}
 const latest=(i=0)=>snapshots[i].at(-1)!;const evidence:{[key:string]:unknown}={status:'RUNNING',runId,port,scope:'Rebuilt item3 ordinary Digit5/useItem5 clears real2007 burn after first70 tick, owned/battle2→1 persisted before cleanse; repeated no-status rejection preserves stock; two natural rounds and sameDB token restart; explicit held items and HP600 source fixture'};
 try{
 await start();const accounts:{accountId:string;token:string}[]=[];for(const c of clients.slice(0,3)){assert((await c.connect()).isSucc);const a=await c.callApi('Account',{});assert(a.isSucc);accounts.push(a.res);}
 const template=JSON.parse(readFileSync('recovery/output/world-role-attributes-native.json','utf8')).rows.find((r:{tankId:number;part:number})=>r.tankId===1&&r.part===0);const store=new AccountStore(database);
 const base=new Map<number,number>(Object.keys(template.base).map(k=>[Number(k),0])),equipment=new Map<number,number>(Object.keys(template.equipment).map(k=>[Number(k),0]));base.set(0,73);base.set(8,1);base.set(0x2c,600);base.set(0x34,5);base.set(0x3c,10);equipment.set(0x1c,74);equipment.set(0x24,1);equipment.set(0x3c,100);equipment.set(0x40,70);equipment.set(0x4c,15);equipment.set(0x50,30);equipment.set(0x58,2001);
 try{for(const [i,account]of accounts.slice(0,2).entries()){store.replaceRoleRecords(account.accountId,{base:[{name:'Explicit base pet1 fixture',fields:base}],equipment:[{name:'Explicit base tank1 fixture',fields:equipment}]});store.replaceInventory(account.accountId,[{instanceId:i===0?77:78,itemTableId:i===0?2007:3,ownedQuantity:i===0?1:2,battleQuantity:i===0?1:2,state:0,field8:0,float24Bits:0,float28Bits:0,float2cBits:0}]);const bytes=new Uint8Array(0x170),view=new DataView(bytes.buffer);view.setUint32(0xa4,73,true);view.setUint32(0xa8,74,true);store.replaceRoleProfile(account.accountId,{bytes,strings:['','']});}}finally{store.close();}
 evidence.fixture={source:'tank-numeric-sol-network.cts measured pet1HP600 fixture; world-role-attributes-native complete field layout',base:[...base],equipment:[...equipment],initialOwned2007:1,instanceId:77};assert((await clients[0].callApi('Kitbag',{operation:'ASSIGN',slot:1,instanceId:77})).isSucc);assert((await clients[1].callApi('Kitbag',{operation:'ASSIGN',slot:4,instanceId:78})).isSucc);
 const created=await clients[0].callApi('CreateRoom',{mode:4,mapId:7,name:'燃烧发射者',tankId:1,roomName:'2007持续伤害'});assert(created.isSucc);const roomId=created.res.room.id,ownerId=created.res.playerId;const joined=await clients[1].callApi('Join',{roomId,clientId:'ignored',name:'燃烧目标',tankId:1});assert(joined.isSucc);const targetId=joined.res.playerId;
 assert((await clients[0].callApi('Autopilot',{round:1,enabled:true})).isSucc);for(const c of clients.slice(0,2))assert((await c.callApi('Ready',{round:1,isReady:true})).isSucc);await wait(()=>latest()?.phase==='PLAYING');evidence.initial=latest();assert(latest().players.every(p=>p.maxHp===(600)));
 await wait(()=>events[0].filter(e=>e.type==='fire'&&e.playerId===ownerId&&e.skillId===2007).length===(1),20000);assert((await clients[0].callApi('Autopilot',{round:1,enabled:false})).isSucc);assert((await clients[0].sendMsg('PlayerInput',{sequence:1,move:0,turn:0,aim:0,fire:false,useItem:0,clientTime:Date.now()})).isSucc);evidence.stopAfterNatural2007=latest();
 await wait(()=>events[0].some(e=>e.type==='hit'&&e.playerId===ownerId&&e.targetId===targetId),10000);const initialHit=timed.find(r=>r.page===0&&r.event.type==='hit'&&r.event.playerId===ownerId&&r.event.targetId===targetId)!;evidence.initialHit=initialHit; await wait(()=>events[0].filter(e=>e.type==='hit'&&e.skillId===4005).length===1,8000);evidence.beforeInjection=latest();assert.equal(latest().players.find(p=>p.id===targetId)!.hp,487);assert((await clients[1].sendMsg('PlayerInput',{sequence:1,move:0,turn:0,aim:0,fire:false,useItem:5,clientTime:Date.now()})).isSucc);await wait(()=>events[0].some(e=>e.type==='itemUsed'&&e.skillId===3));evidence.used=events[0].find(e=>e.type==='itemUsed'&&e.skillId===3);const inventory=await clients[1].callApi('Inventory',{});assert(inventory.isSucc);assert.equal(inventory.res.records[0].ownedQuantity,1);assert.equal(inventory.res.records[0].battleQuantity,1);evidence.afterInventory=inventory.res;const persisted=new AccountStore(database);try{assert.equal(persisted.inventory(accounts[1].accountId).records[0].ownedQuantity,1);}finally{persisted.close();}
 assert((await clients[1].sendMsg('PlayerInput',{sequence:2,move:0,turn:0,aim:0,fire:false,useItem:5,clientTime:Date.now()})).isSucc);await wait(()=>events[0].some(e=>e.type==='itemRejected'&&e.playerId===targetId));evidence.rejected=events[0].find(e=>e.type==='itemRejected'&&e.playerId===targetId);const repeat=await clients[1].callApi('Inventory',{});assert(repeat.isSucc);assert.deepEqual(repeat.res,inventory.res);const until=latest().tick+200;await wait(()=>latest().tick>=until,12000);assert.equal(events[0].filter(e=>e.type==='hit'&&e.skillId===4005).length,1);assert.equal(latest().players.find(p=>p.id===targetId)!.hp,487);evidence.cleansed=latest();
 await wait(()=>latest().phase==='FINISHED',40000);evidence.finished=latest();for(const c of clients.slice(0,2))assert((await c.callApi('Rematch',{round:1})).isSucc);await wait(()=>latest().phase==='PLAYING'&&latest().match?.round===2);evidence.rematch=latest();assert(latest().players.every(p=>p.hp===600));await wait(()=>latest().phase==='FINISHED'&&latest().match?.round===2,40000);evidence.round2Finished=latest();assert.equal(events[0].filter(e=>e.type==='hit'&&e.skillId===4005).length,1);const shared=(i:number)=>events[i].filter(e=>['fire','hit','ammoConsumed','itemUsed','itemRejected','finish'].includes(e.type));assert.deepEqual(shared(0),shared(1));evidence.sharedEvents=shared(0);for(const c of clients.slice(0,2))assert((await c.callApi('Leave',{roomId,round:2})).isSucc);await Promise.all(clients.map(c=>c.disconnect()));await stop();await start();assert((await clients[1].connect()).isSucc);assert((await clients[1].callApi('Account',{token:accounts[1].token})).isSucc);const restored=await clients[1].callApi('Inventory',{});assert(restored.isSucc);assert.equal(restored.res.records[0].ownedQuantity,1);assert.equal(restored.res.hotkeys[3],78);evidence.actualRestart=restored.res;evidence.status='PASS';console.log(JSON.stringify({status:'PASS',output,injectionOwned:1,cleansedHp:487}));
 }catch(error){evidence.status='FAIL';evidence.error=String(error);throw error;}finally{evidence.snapshots=snapshots;evidence.events=events;evidence.timed=timed;await Promise.allSettled(clients.map(c=>c.disconnect()));await stop();writeFileSync(output+'.json',JSON.stringify(evidence,null,2)+'\n');writeFileSync(output+'.log',log);rmSync(dir,{recursive:true,force:true});}
}main().catch(e=>{console.error(e);process.exitCode=1;});
