import assert from 'node:assert/strict';
import {spawn,type ChildProcess} from 'node:child_process';
import {mkdtempSync,rmSync,writeFileSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {WsClient} from 'tsrpc';
import {serviceProto} from '../apps/shared/protocols/serviceProto';
import {AccountStore} from '../apps/server/src/account-store';
import type {MsgRoomSnapshot,MsgRoomEvent} from '../apps/shared/protocols';
async function main(){
 
 const runId=new Date().toISOString().replace(/[:.]/g,'-'),output='recovery/output/pet-purchase-network-'+runId,dir=mkdtempSync(join(tmpdir(),'cdtank-pet-purchase-')),database=join(dir,'accounts.sqlite'),port=3243;let server:ChildProcess|undefined,log='';
 const clients=Array.from({length:4},()=>new WsClient(serviceProto,{server:`ws://127.0.0.1:${port}`,logger:undefined,heartbeat:{interval:5000,timeout:10000}}));const snapshots:MsgRoomSnapshot[][]=clients.map(()=>[]),events:MsgRoomEvent[][]=clients.map(()=>[]),timed:{page:number;tick:number;receivedAt:number;event:MsgRoomEvent}[]=[];clients.forEach((c,i)=>{c.listenMsg('RoomSnapshot',s=>{snapshots[i].push(s);});c.listenMsg('RoomEvent',e=>{events[i].push(e);timed.push({page:i,tick:snapshots[i].at(-1)?.tick??0,receivedAt:Date.now(),event:e});});});
 async function wait(f:()=>boolean,ms=10000){const end=Date.now()+ms;while(!f()&&Date.now()<end)await new Promise(r=>setTimeout(r,25));assert(f(),log.slice(-1000));}async function stop(){if(server?.exitCode===null&&server.signalCode===null){const end=new Promise<void>(r=>server!.once('exit',()=>r()));server.kill();await end;}}async function start(){const startOffset=log.length;server=spawn(process.execPath,['--import','tsx','apps/server/src/index.ts'],{env:{...process.env,PORT:String(port),ACCOUNT_DB_PATH:database,MATCH_TIME_LIMIT_SECONDS:'30'},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>{log+=String(d);});server.stderr!.on('data',d=>{log+=String(d);});await wait(()=>log.slice(startOffset).includes(`Server started at ${port}.`));}
 const latest=(i=0)=>snapshots[i].at(-1)!;const evidence:{[key:string]:unknown}={status:'RUNNING',runId,port,scope:'Rebuilt MONEY3500 pet2 BUY-created complete base ownership, no preownedpet2; normal Home selection, map7 two-account room+CPU move/fire/naturalhit sharedHP700 authority, Leave and actual sameDB token restore'};
 try{
 await start();const accounts:{accountId:string;token:string}[]=[];for(const c of clients.slice(0,3)){assert((await c.connect()).isSucc);const a=await c.callApi('Account',{});assert(a.isSucc);accounts.push(a.res);}
 const template=JSON.parse(readFileSync('recovery/output/world-role-attributes-native.json','utf8')).rows.find((r:{tankId:number;part:number})=>r.tankId===1&&r.part===0);const store=new AccountStore(database);
 const base=new Map<number,number>(Object.keys(template.base).map(k=>[Number(k),0])),equipment=new Map<number,number>(Object.keys(template.equipment).map(k=>[Number(k),0]));base.set(0,73);base.set(8,1);base.set(0x2c,600);base.set(0x34,5);base.set(0x3c,10);equipment.set(0x1c,74);equipment.set(0x24,1);equipment.set(0x3c,100);equipment.set(0x40,70);equipment.set(0x4c,15);equipment.set(0x50,30);equipment.set(0x58,2001);
 try{for(const [i,account]of accounts.entries()){store.replaceRoleRecords(account.accountId,{base:[{name:'Explicit base pet1 fixture',fields:base}],equipment:[{name:'Explicit base tank1 fixture',fields:equipment}]});assert.equal(store.inventory(account.accountId).records.length,0);const bytes=new Uint8Array(0x170),view=new DataView(bytes.buffer);view.setUint32(0xa4,73,true);view.setUint32(0xa8,74,true);view.setUint32(0x70,i===0?4000:i===1?3000:4000,true);view.setUint32(0x74,1000,true);store.replaceRoleProfile(account.accountId,{bytes,strings:['','']});}const capBase=Array.from({length:10},(_,i)=>({name:'Explicit pet1 capacity fixture',fields:new Map([...base].map(([offset,value])=>[offset,offset===0?100+i:value]))}));store.replaceRoleRecords(accounts[2].accountId,{base:capBase,equipment:[{name:'Explicit base tank1 fixture',fields:equipment}]});}finally{store.close();}
 evidence.fixture={source:'explicit previously measured sourcepet1HP600/tank1 complete layout',base:[...base],equipment:[...equipment],money:[4000,3000,4000],tokens:1000,initialOwnedPet2:false};
 assert((await clients[3].connect()).isSucc);const unauth=await clients[3].callApi('PetShop',{operation:'QUERY'});assert(!unauth.isSucc&&unauth.err.code==='ACCOUNT_REQUIRED');evidence.unauthenticated=unauth;
 const query=await clients[0].callApi('PetShop',{operation:'QUERY'});assert(query.isSucc);assert.equal(query.res.pets.length,1);assert.equal(query.res.pets[0].petId,2);assert.equal(query.res.pets[0].moneyPrice,3500);assert.equal(query.res.pets[0].tokenPrice,350);evidence.catalog=query.res;const request={operation:'BUY' as const,petId:2,currency:'MONEY' as const,requestId:'pet2_money_0001'};
 const token=await clients[0].callApi('PetShop',{...request,currency:'TOKENS',requestId:'pet2_token_0001'});assert(!token.isSucc);const invalid=await clients[0].callApi('PetShop',{...request,petId:1,requestId:'pet2_invalid_0001'});assert(!invalid.isSucc);const shortage=await clients[1].callApi('PetShop',{...request,requestId:'pet2_shortage_0001'});assert(!shortage.isSucc);const badRequestId=await clients[0].callApi('PetShop',{...request,requestId:'x'});assert(!badRequestId.isSucc);const capped=await clients[2].callApi('PetShop',{...request,requestId:'pet2_capped_0001'});assert(!capped.isSucc);const capOwned=await clients[2].callApi('OwnedRoles',{});assert(capOwned.isSucc&&capOwned.res.base.length===10);const capBalance=await clients[2].callApi('PetShop',{operation:'QUERY'});assert(capBalance.isSucc&&capBalance.res.money===4000);evidence.rejected={token,invalid,shortage,badRequestId,capped,capOwned,capBalance};
 const paid=await clients[0].callApi('PetShop',request);assert(paid.isSucc);assert.equal(paid.res.money,500);assert.equal(paid.res.tokens,1000);const bought=paid.res.purchased!,fields=new Map(bought.fields),instanceId=fields.get(0)!;assert(instanceId!==73);assert.equal(fields.size,31);assert.equal(fields.get(8),2);assert.deepEqual([fields.get(0x2c),fields.get(0x34),fields.get(0x3c)],[700,20,8]);const source=JSON.parse(readFileSync('recovery/output/pet-purchase-source-sol.json','utf8')).pet.values;for(let slot=0;slot<6;slot++){assert.equal(fields.get(0x44+slot*4),Number(source['Skill'+slot]));assert.equal(fields.get(0x5c+slot*4),0);}for(const[offset,value]of fields)if(![0,8,0x2c,0x34,0x3c,...Array.from({length:6},(_,i)=>0x44+i*4),...Array.from({length:6},(_,i)=>0x5c+i*4)].includes(offset))assert.equal(value,0);evidence.purchase=paid.res;
 const replay=await clients[0].callApi('PetShop',request);assert(replay.isSucc&&replay.res.replayed&&replay.res.money===500);assert.deepEqual(replay.res.purchased,bought);const conflict=await clients[0].callApi('PetShop',{...request,currency:'TOKENS'});assert(!conflict.isSucc);evidence.idempotency={replay,conflict};
 const owned=await clients[0].callApi('OwnedRoles',{});assert(owned.isSucc);assert.equal(owned.res.base.length,2);assert.deepEqual(owned.res.base.find(r=>new Map(r.fields).get(0)===instanceId),bought);const peerOwned=await clients[1].callApi('OwnedRoles',{});assert(peerOwned.isSucc&&peerOwned.res.base.length===1);const peerBalance=await clients[1].callApi('PetShop',{operation:'QUERY'});assert(peerBalance.isSucc&&peerBalance.res.money===3000&&peerBalance.res.tokens===1000);const peerSelect=await clients[1].callApi('SelectRole',{kind:'pet',instanceId});assert(!peerSelect.isSucc);evidence.accountIsolation={peerOwned:peerOwned.res,peerBalance:peerBalance.res,peerSelect};
 const profileBefore=await clients[0].callApi('RoleProfile',{});assert(profileBefore.isSucc);assert.equal(new DataView(Uint8Array.from(profileBefore.res.profile!.bytes).buffer).getUint32(0xa4,true),73);const selected=await clients[0].callApi('SelectRole',{kind:'pet',instanceId});assert(selected.isSucc);assert.equal(new DataView(Uint8Array.from(selected.res.profile.bytes).buffer).getUint32(0xa4,true),instanceId);evidence.selected=selected.res;
 const created=await clients[0].callApi('CreateRoom',{mode:4,mapId:7,name:'购买宠物',tankId:1,roomName:'付费宠物'});evidence.created=created;assert(created.isSucc);const roomId=created.res.room.id,ownerId=created.res.playerId;const joined=await clients[1].callApi('Join',{clientId:'pet-peer',name:'生命观察',tankId:1,roomId});assert(joined.isSucc);const cpu=await clients[0].callApi('Cpu',{round:1,operation:'ADD',tankId:1});assert(cpu.isSucc);assert((await clients[1].callApi('Ready',{round:1,isReady:true})).isSucc);assert((await clients[0].callApi('Ready',{round:1,isReady:true})).isSucc);await wait(()=>latest()?.phase==='PLAYING');evidence.initial=latest();const player=()=>latest().players.find(p=>p.id===ownerId)!;assert.equal(player().tankId,1);assert.equal(player().hp,700);assert.equal(player().maxHp,700);
 const gated=await clients[0].callApi('PetShop',{...request,requestId:'pet2_playing_0001'});assert(!gated.isSucc);evidence.playingReject=gated;
 const before=player();assert((await clients[0].sendMsg('PlayerInput',{sequence:1,move:1,turn:0,aim:0,fire:false,useItem:0,clientTime:Date.now()})).isSucc);const until=latest().tick+20;await wait(()=>latest().tick>=until);const after=player();assert(Math.hypot(after.x-before.x,after.z-before.z)>0.1);assert((await clients[0].sendMsg('PlayerInput',{sequence:2,move:0,turn:0,aim:0,fire:true,useItem:0,clientTime:Date.now()})).isSucc);await wait(()=>events[0].some(e=>e.type==='fire'&&e.playerId===ownerId));assert((await clients[0].sendMsg('PlayerInput',{sequence:3,move:0,turn:0,aim:0,fire:false,useItem:0,clientTime:Date.now()})).isSucc);await wait(()=>events[0].some(e=>e.type==='hit'&&e.targetId===ownerId)&&player().hp<700,20000);await wait(()=>snapshots[0].some(a=>snapshots[1].some(b=>a.tick===b.tick&&a.players.find(p=>p.id===ownerId)!.hp<700&&a.players.find(p=>p.id===ownerId)!.hp===b.players.find(p=>p.id===ownerId)!.hp)));const shared=snapshots[0].find(a=>snapshots[1].some(b=>a.tick===b.tick&&a.players.find(p=>p.id===ownerId)!.hp<700&&a.players.find(p=>p.id===ownerId)!.hp===b.players.find(p=>p.id===ownerId)!.hp))!;evidence.normalBattle={before,after,fire:events[0].find(e=>e.type==='fire'&&e.playerId===ownerId),hit:events[0].find(e=>e.type==='hit'&&e.targetId===ownerId),sharedOwnerHealth:{tick:shared.tick,owner:shared.players.find(p=>p.id===ownerId),peer:snapshots[1].find(b=>b.tick===shared.tick)!.players.find(p=>p.id===ownerId)},latest:latest()};assert((await clients[1].callApi('Leave',{roomId,round:1})).isSucc);assert((await clients[0].callApi('Leave',{roomId,round:1})).isSucc);
 await Promise.all(clients.map(c=>c.disconnect()));await stop();await start();assert((await clients[0].connect()).isSucc);assert((await clients[0].callApi('Account',{token:accounts[0].token})).isSucc);const restoredOwned=await clients[0].callApi('OwnedRoles',{});assert(restoredOwned.isSucc);assert.deepEqual(restoredOwned.res.base.find(r=>new Map(r.fields).get(0)===instanceId),bought);const restoredProfile=await clients[0].callApi('RoleProfile',{});assert(restoredProfile.isSucc);assert.equal(new DataView(Uint8Array.from(restoredProfile.res.profile!.bytes).buffer).getUint32(0xa4,true),instanceId);const restoredBalance=await clients[0].callApi('PetShop',{operation:'QUERY'});assert(restoredBalance.isSucc&&restoredBalance.res.money===500&&restoredBalance.res.tokens===1000);evidence.actualRestart={owned:restoredOwned.res,profile:restoredProfile.res,money:restoredBalance.res.money,tokens:restoredBalance.res.tokens};evidence.status='PASS';console.log(JSON.stringify({status:'PASS',output,instanceId,money:500}));
 }catch(error){evidence.status='FAIL';evidence.error=String(error);throw error;}finally{evidence.snapshots=snapshots;evidence.events=events;evidence.timed=timed;await Promise.allSettled(clients.map(c=>c.disconnect()));await stop();writeFileSync(output+'.json',JSON.stringify(evidence,null,2)+'\n');writeFileSync(output+'.log',log);rmSync(dir,{recursive:true,force:true});}
}main().catch(e=>{console.error(e);process.exitCode=1;});
