import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync,rmSync,writeFileSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {WsClient} from 'tsrpc';
import {serviceProto} from '../apps/shared/protocols/serviceProto';
import {AccountStore} from '../apps/server/src/account-store';
import {readOwnedRolePairMessage} from '../recovery/evidence/roles/role-owned-sources';
import type {MsgRoomSnapshot,MsgRoomEvent} from '../apps/shared/protocols';
async function main(){
 const dir=mkdtempSync(join(tmpdir(),'cdtank-preparation-health-')),port=3216,database=join(dir,'accounts.sqlite');let log='';
 const observer=join(dir,'observe.ts');writeFileSync(observer,`import {World} from ${JSON.stringify(resolve('apps/server/src/world.ts'))};const original=World.prototype.snapshot;World.prototype.snapshot=function(...args){const result=original.apply(this,args);if(result){const room=this.rooms.get(result.roomId);console.log('HEALTH_OBSERVATION '+JSON.stringify({roomId:result.roomId,tick:result.tick,phase:result.phase,round:result.match.round,players:[...room.players.values()].map(p=>({id:p.id,hp:p.hp,recordHp:p.attributes.record.hp,maxHp:p.attributes.record.maxHp,roleHp:p.combat.record?.numericFields?.get(0x54),roleMaxHp:p.combat.record?.numericFields?.get(0x58),attributesReady:p.attributesReady}))}));}return result;};void import(${JSON.stringify(resolve('apps/server/src/index.ts'))});`);
 const server=spawn(process.execPath,['--import',resolve('node_modules/tsx/dist/loader.mjs'),observer],{env:{...process.env,PORT:String(port),ACCOUNT_DB_PATH:database,MATCH_TIME_LIMIT_SECONDS:'20'},stdio:['ignore','pipe','pipe']});server.stdout.on('data',d=>{log+=String(d);});server.stderr.on('data',d=>{log+=String(d);});
 const clients=Array.from({length:3},()=>new WsClient(serviceProto,{server:`ws://127.0.0.1:${port}`,logger:undefined,heartbeat:{interval:5000,timeout:10000}}));
 const snapshots:MsgRoomSnapshot[][]=clients.map(()=>[]),events:MsgRoomEvent[][]=clients.map(()=>[]);clients.forEach((c,i)=>{c.listenMsg('RoomSnapshot',s=>snapshots[i].push(s));c.listenMsg('RoomEvent',e=>events[i].push(e));});
 const latest=(i=0)=>snapshots[i].at(-1)!;async function wait(f:()=>boolean,ms=10000){const end=Date.now()+ms;while(!f()&&Date.now()<end)await new Promise(r=>setTimeout(r,30));assert(f(),log.slice(-1000));}
 const evidence:{[key:string]:unknown}={port,scope:'M2-01-PREP actual index; reused native owned account fixture, normal Equipment/CreateRoom/Join/Ready/CPU/Autopilot/Rematch/Leave;20s legal deadline; readonly role health observer'};
 try{
 await wait(()=>log.includes(`Server started at ${port}.`));const accounts=[];for(const c of clients){assert((await c.connect()).isSucc);const a=await c.callApi('Account',{});assert(a.isSucc);accounts.push(a.res);}
 const store=new AccountStore(database);try{for(const owner of [accounts[0],accounts[2]]){
 const fixture=JSON.parse(readFileSync('recovery/output/role-owned-pair-native.json','utf8')).rows[0],pair=readOwnedRolePairMessage(new Uint8Array(fixture.raw),fixture.alignment,()=> '原角色');const base={name:'测试宠物',fields:new Map(pair.base.fields)},tank={name:'测试战车',fields:new Map(pair.equipment.fields)};base.fields.set(0,71);base.fields.set(8,1);tank.fields.set(0x1c,72);tank.fields.set(0x24,2);tank.fields.set(0x28,20011);tank.fields.set(0x2c,20012);tank.fields.set(0x30,20013);tank.fields.set(0x6c,3);for(const offset of [0x58,0x5c,0x60])tank.fields.set(offset,0);for(let slot=0;slot<6;slot++){base.fields.set(0x44+slot*4,0);base.fields.set(0x5c+slot*4,0);}store.replaceRoleRecords(owner.accountId,{base:[base],equipment:[tank]});const profile={bytes:new Uint8Array(0x170),strings:['角色名','资料'] as [string,string]};const view=new DataView(profile.bytes.buffer);view.setUint32(0xa4,71,true);view.setUint32(0xa8,72,true);store.replaceRoleProfile(owner.accountId,profile);store.replaceInventory(owner.accountId,[13001,13002,14001,10001,10002,12001].map((itemTableId,index)=>({instanceId:81+index,itemTableId,ownedQuantity:1,battleQuantity:1,state:0,field8:0,float24Bits:0,float28Bits:0,float2cBits:0})));}}finally{store.close();}
 evidence.fixture={source:'role-owned-pair-native.json rows0;browser-home-equipment existing fixture',petInstanceId:71,tankInstanceId:72,tankId:2,inventoryInstances:[81,82,83,84,85,86]};
 for(const c of [clients[0],clients[2]])assert((await c.callApi('Equipment',{operation:'EQUIP',slot:1,instanceId:83})).isSucc);
 const created=await clients[0].callApi('CreateRoom',{mode:4,mapId:7,name:'装备甲',tankId:1,roomName:'装备生命验收'});assert(created.isSucc);const roomId=created.res.room.id,ownerId=created.res.playerId;
 assert((await clients[1].callApi('Join',{roomId,clientId:'ignored',name:'装备乙',tankId:1})).isSucc);
 for(const tankId of [1,105])assert((await clients[0].callApi('Cpu',{round:1,operation:'ADD',tankId})).isSucc);await wait(()=>latest()?.players.length===4);evidence.waiting=latest();const owner=()=>latest().players.find(p=>p.id===ownerId)!;assert.equal(owner().hp,owner().maxHp);assert(owner().hp<=owner().maxHp);
 const fallback=latest().players.find(p=>!p.isCpu&&p.id!==ownerId)!;assert.equal(fallback.hp,fallback.maxHp);evidence.incompleteSourceFallback=fallback;
 assert((await clients[0].callApi('Ready',{round:1,isReady:true})).isSucc);await wait(()=>latest().match!.readyPlayerIds.includes(ownerId));
 assert((await clients[0].callApi('Equipment',{operation:'UNEQUIP',slot:1})).isSucc);await wait(()=>!latest().match!.readyPlayerIds.includes(ownerId));evidence.unequipped=latest();assert.equal(owner().hp,owner().maxHp);
 assert((await clients[0].callApi('Equipment',{operation:'EQUIP',slot:1,instanceId:83})).isSucc);evidence.reequipped=latest();assert.equal(owner().hp,owner().maxHp);
 for(const c of clients.slice(0,2))assert((await c.callApi('Autopilot',{round:1,enabled:true})).isSucc);for(const c of clients.slice(0,2))assert((await c.callApi('Ready',{round:1,isReady:true})).isSucc);
 await wait(()=>snapshots[0].some(s=>s.phase==='PLAYING'));evidence.initial=snapshots[0].find(s=>s.phase==='PLAYING');
 const rejected=await clients[0].callApi('Equipment',{operation:'UNEQUIP',slot:1});assert(!rejected.isSucc);evidence.playingEquipmentRejected=rejected;
 await wait(()=>owner().hp<owner().maxHp&&latest().phase==='PLAYING',15000);const beforeInventory=owner().hp;assert((await clients[0].callApi('Inventory',{})).isSucc);await wait(()=>owner().hp<=beforeInventory);evidence.liveInventoryQuery={beforeHp:beforeInventory,after:owner()};await wait(()=>latest().phase==='FINISHED',35000);evidence.finished=latest();assert(events[0].some(e=>e.type==='fire'));assert(events[0].some(e=>e.type==='hit'));
 const finishedRejected=await clients[0].callApi('Equipment',{operation:'UNEQUIP',slot:1});assert(!finishedRejected.isSucc);evidence.finishedEquipmentRejected=finishedRejected;
 assert((await clients[0].callApi('Inventory',{})).isSucc);evidence.finishedInventoryQuery=owner();
 const arrived=await clients[2].callApi('Join',{roomId,clientId:'ignored',name:'装备新客',tankId:1});assert(arrived.isSucc);await wait(()=>latest(2)?.phase==='FINISHED');const newcomer=latest(2).players.find(p=>p.id===arrived.res.playerId)!;assert.equal(newcomer.hp,newcomer.maxHp);evidence.newFinishedParticipant=newcomer;assert((await clients[2].callApi('Leave',{roomId,round:1})).isSucc);
 for(const c of clients.slice(0,2))assert((await c.callApi('Rematch',{round:1})).isSucc);await wait(()=>snapshots[0].some(s=>s.match?.round===2&&s.phase==='PLAYING'));evidence.rematch=snapshots[0].find(s=>s.match?.round===2&&s.phase==='PLAYING');const reset=(evidence.rematch as MsgRoomSnapshot).players.find(p=>p.id===ownerId)!;assert.equal(reset.hp,reset.maxHp);
 await wait(()=>latest().match?.round===2&&latest().phase==='FINISHED',35000);evidence.round2Finished=latest();for(const c of clients.slice(0,2))assert((await c.callApi('Leave',{roomId,round:2})).isSucc);
 const observations=log.split('\n').filter(line=>line.startsWith('HEALTH_OBSERVATION ')).map(line=>JSON.parse(line.slice(19)));for(const s of observations)for(const p of s.players){assert(p.hp>=0&&p.hp<=p.maxHp,JSON.stringify(p));assert.equal(p.hp,p.recordHp);assert.equal(p.hp,p.roleHp);assert.equal(p.maxHp,p.roleMaxHp);}evidence.roleObservations=observations;evidence.status='PASS';console.log(JSON.stringify({status:'PASS',waiting:evidence.waiting,roleObservationCount:observations.length}));
 }catch(error){evidence.status='FAIL';evidence.error=String(error);throw error;}finally{evidence.snapshots=snapshots;evidence.events=events;await Promise.allSettled(clients.map(c=>c.disconnect()));if(server.exitCode===null){const end=new Promise<void>(r=>server.once('exit',()=>r()));server.kill();await end;}writeFileSync('recovery/output/preparation-health-network.json',JSON.stringify(evidence,null,2)+'\n');writeFileSync('recovery/output/preparation-health-network.log',log);rmSync(dir,{recursive:true,force:true});}
}main().catch(e=>{console.error(e);process.exitCode=1;});
