import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {BattleHud} from '../apps/web/src/interface/battle/battle-hud';
import type {SourceUi} from '../apps/web/src/interface/battle/battle-hud';
import type {MsgRoomSnapshot, PlayerSnapshot} from '../apps/shared/protocols/MsgRoomSnapshot';

const data = JSON.parse(readFileSync('recovery/output/web-assets/ui.json', 'utf8')) as SourceUi;
const originalFetch = globalThis.fetch;
let resolveUi: ((value: Response) => void) | undefined;
let deferred = false;
globalThis.fetch = (async (url: string) => {
  if (url === '/ui-fonts.json') return {ok: true, json: async () => ({fonts: []})} as Response;
  if (deferred) return new Promise<Response>(resolve => {resolveUi = resolve;});
  return {ok: true, json: async () => data} as Response;
}) as typeof fetch;
const player = (id: string, team: number): PlayerSnapshot => ({id, name: id, tankId: 1, petId: 1, team,
  x: 0, y: 0, z: 0, yaw: 0, aim: 0, hp: 300, maxHp: 300, alive: true, score: 0, kills: 0, deaths: 0,
  respawnAt: 0, isVIP: false});
const event = (type: string, message: string, playerId = 'local', targetId = 'enemy') => ({roomId: 'test', type, message, playerId, targetId, value: 0, x: 0, y: 0, z: 0});
async function run() {
  const hud = new BattleHud();
  let count = 0, reloadCount = 0;
  hud.subscribe(() => count++); hud.subscribeReload(() => reloadCount++);
  assert.equal(hud.getSnapshot(), hud.getSnapshot());
  await hud.load(); assert.equal(hud.getSnapshot().data, data);
  const local = player('local', 0), ally1 = player('ally1', 0), ally2 = player('ally2', 0), enemy = player('enemy', 1);
  let snapshot = {mode: 1, remaining: 60, phase: 'PLAYING', serverTime: 10000,
    players: [ally1, ally2, local, enemy], match: {round: 1, teamLives: [30, 29]}} as MsgRoomSnapshot;
  hud.update(snapshot, 'local', 1000);
  assert.deepEqual(hud.getSnapshot().slots.slice(0, 3).map(slot => slot?.id), ['local', 'ally2', 'ally1'], 'local swaps with team slot zero');
  assert.equal(hud.getSnapshot().slots[6]?.id, 'enemy');
  assert.deepEqual(hud.getSnapshot().teamCounts, {self: '30', enemy: '29'});
  const base = hud.getSnapshot(), baseCount = count;
  hud.update({...snapshot, serverTime: 10001, players: snapshot.players.map(value => ({...value, x: 123, score: 50}))}, 'local', 1010);
  assert.equal(hud.getSnapshot(), base, 'movement and invisible fields do not notify');
  assert.equal(count, baseCount);
  local.reload = {duration: 2, remaining: 2, startedAt: 10000, source: 'rebuilt'};
  hud.update(snapshot, 'local', 1020);
  const beforeReload = count, oldReload = hud.getReloadSnapshot();
  hud.update({...snapshot, serverTime: 10100}, 'local', 1100);
  assert.equal(count, beforeReload, 'reload progress cannot rerender full HUD');
  assert.notEqual(hud.getReloadSnapshot(), oldReload); assert.ok(reloadCount >= 2);
  hud.event(event('fire', '开火'));
  hud.update(snapshot, 'local', 1110);
  assert.equal(hud.getSnapshot().slots[0]?.expression, 'attack');
  hud.update(snapshot, 'local', 1800);
  assert.equal(hud.getSnapshot().slots[0]?.expression, 'normal');
  local.hp = 20; hud.update(snapshot, 'local', 1810);
  assert.equal(hud.getSnapshot().localHealth?.hp, 20);
  local.alive = false; hud.update(snapshot, 'local', 1820);
  assert.equal(hud.getSnapshot().slots[0]?.asset, data.portraitDeath.local);
  assert.equal(hud.getReloadSnapshot().visible, false);
  local.alive = true; local.hp = 300; hud.update(snapshot, 'local', 1830);
  assert.equal(hud.getSnapshot().slots[0]?.expression, 'normal');
  hud.update({...snapshot, remaining: 29}, 'local', 1840);
  assert.equal(hud.getSnapshot().timers[0].colour, 'ffff0000');
  hud.update({...snapshot, remaining: 40}, 'local', 1850);
  assert.equal(hud.getSnapshot().timers[0].colour, 'ffff0000', 'native >=30 branch retains prior colour');
  for (let index = 0; index < 7; index++) hud.event(event('chat', String(index)));
  assert.equal(hud.getSnapshot().messages, '2\n3\n4\n5\n6');
  let opacityCount = 0;
  hud.subscribeBattleInfoOpacity(() => opacityCount++);
  const beforeFade = count;
  hud.update({...snapshot, remaining: 40}, 'local', 9850);
  assert.equal(hud.getBattleInfoOpacity(), Math.fround(.2));
  assert.equal(count, beforeFade, 'opacity clock cannot rerender full HUD');
  hud.battleInfoHover(true);
  hud.update({...snapshot, remaining: 40}, 'local', 10850);
  assert.equal(hud.getBattleInfoOpacity(), 1);
  hud.battleInfoHover(false);
  hud.event(event('fire', '开火'));
  assert.equal(hud.getBattleInfoOpacity(), Math.fround(.2), 'filtered fire does not reset messages');
  hud.event(event('chat', '新消息'));
  assert.equal(hud.getBattleInfoOpacity(), 1);
  assert.equal(opacityCount, 4);
  hud.clear();
  assert.equal(hud.getBattleInfoOpacity(), 1);
  assert.equal(hud.getSnapshot().visible, false); assert.equal(hud.getSnapshot().messages, '');
  assert.equal(hud.getSnapshot().timers[0].colour, undefined); assert.equal(hud.getSnapshot().teamCounts, undefined);
  hud.update({...snapshot, phase: 'FINISHED'}, 'local', 100000);
  assert.equal(hud.getSnapshot().slots[0]?.expression, 'normal', 'clear resets portrait clock');
  assert.equal(hud.getReloadSnapshot().visible, false);
  // Portrait identity comes from selected PetTable definition, independently of the tank.
  const pets = new BattleHud(); await pets.load();
  const localPet = player('local', 0), remotePet = player('remote', 1);
  localPet.petId = 2; remotePet.petId = 1;
  const petSnapshot = {...snapshot, players: [localPet, remotePet]};
  const pet1 = data.portraits.find(value => value.petId === 1)!;
  const pet2 = data.portraits.find(value => value.petId === 2)!;
  pets.update(petSnapshot, 'local', 0);
  assert.equal(pets.getSnapshot().slots[0]?.asset, pet2.asset, 'same tank uses selected local pet2');
  assert.equal(pets.getSnapshot().slots[6]?.asset, pet1.remoteAsset, 'remote uses its own pet1 normal1');
  assert.equal(pets.getSnapshot().slots[0]?.petId, 2);
  pets.event(event('fire', ''));
  pets.update(petSnapshot, 'local', 0);
  assert.equal(pets.getSnapshot().slots[0]?.expression, 'attack');
  localPet.tankId = 3; pets.update(petSnapshot, 'local', 100);
  assert.equal(pets.getSnapshot().slots[0]?.expression, 'attack', 'tank changes retain pet animation');
  assert.equal(pets.getSnapshot().slots[0]?.asset, pet2.expressions.attack);
  localPet.petId = 1; pets.update(petSnapshot, 'local', 100);
  assert.equal(pets.getSnapshot().slots[0]?.expression, 'normal', 'pet changes reset old expression');
  assert.equal(pets.getSnapshot().slots[0]?.asset, pet1.asset);
  for (const petId of [undefined, 999]) {
    localPet.petId = petId; pets.update(petSnapshot, 'local', 100);
    assert.ok(!pets.getSnapshot().slots[0]?.asset, 'missing pet source/asset cannot fall back to tank');
  }
  localPet.petId = 5; pets.update(petSnapshot, 'local', 100);
  assert.equal(pets.getSnapshot().slots[0]?.asset, data.portraits.find(value => value.petId === 5)?.asset, 'pet5 uses exactly its exported source asset');
  localPet.petId = 2; remotePet.petId = 2; pets.update(petSnapshot, 'local', 100);
  assert.equal(pets.getSnapshot().slots[0]?.asset, pet2.asset);
  assert.equal(pets.getSnapshot().slots[6]?.asset, pet2.remoteAsset);
  assert.notEqual(pet2.asset, pet2.remoteAsset);
  pets.event(event('fire', '')); pets.update(petSnapshot, 'local', 100);
  pets.update({...petSnapshot, players: [remotePet]}, 'local', 100);
  pets.update(petSnapshot, 'local', 100);
  assert.equal(pets.getSnapshot().slots[0]?.expression, 'normal', 'departure releases old pet state');
  pets.clear();
  assert.deepEqual(pets.getSnapshot().slots, [], 'Leave releases published player and image references');
  assert.equal(pets.getSnapshot().localHealth, undefined, 'Leave releases the previous local player health');
  pets.update(petSnapshot, 'local', 100);
  assert.equal(pets.getSnapshot().slots[0]?.petId, 2);
  assert.equal(pets.getSnapshot().slots[0]?.expression, 'normal', 're-entry starts with a fresh pet expression');
  const late = new BattleHud(); deferred = true;
  const first = late.load(); late.clear(); resolveUi!({ok: true, json: async () => data} as Response); await first;
  assert.equal(late.getSnapshot().data, undefined, 'clear cancels late resource publication');
  deferred = false; await late.load(); assert.equal(late.getSnapshot().data, data);
  console.log('PASS React HUD semantic projections, slot swap, original portrait/reload rules, isolated progress, timers, log and cancelled load');
}
void run().finally(() => {globalThis.fetch = originalFetch;}).catch(error => {console.error(error); process.exitCode = 1;});
