import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {NullEngine, Scene, VertexBuffer} from '@babylonjs/core';
import {EffectModelLibrary, EffectModelRenderer} from '../apps/web/src/render/effects/models/effect-model-renderer';
import {EffectModelAnimation, effectModelVertices} from '../apps/web/src/render/effects/models/effect-model-animation';
import {SceneCvdAnimation} from '../apps/web/src/assets/scenes/scene-cvd-animation';
import {EFFECT_IDENTITY} from '../apps/web/src/render/effects/common/effect-render-transform';
const library = JSON.parse(readFileSync('recovery/output/web-assets/scene-animation-0007.json', 'utf8')) as EffectModelLibrary;
const resource = library.resources[0];
assert.equal(resource.reference, 'Data/scnobj/obj05025/obj05025.CVD');
assert.equal(resource.nodes.filter(node => node.parts.length).length, 3);
assert.equal(resource.nodes.filter(node => !node.parts.length).length, 20);
for (const node of resource.nodes.filter(node => node.parts.length)) {
  assert.equal(node.frames!.length, 11);
  assert.equal(node.times!.at(-1), node.duration);
  assert.equal(node.animation!.position.mode, 3);
  const clock = new EffectModelAnimation(node.animation!, node.duration!);
  clock.update(node.duration!);
  assert.equal(clock.loops, 0);
  clock.update(.01);
  assert.equal(clock.loops, 1);
  assert(Math.abs(clock.time - .01) < .000001);
  const first = effectModelVertices(node.frames!, node.times!, 0);
  const middle = effectModelVertices(node.frames!, node.times!, .5);
  assert(first.some((vertex, i) => vertex.some((v, j) => v !== middle[i][j])), 'Original vertices must actually animate');
}
const engine = new NullEngine(), scene = new Scene(engine);
const animation = new SceneCvdAnimation(scene, '32', EFFECT_IDENTITY);
const renderer = new EffectModelRenderer(scene, resource, library, new Map(), () => (animation as unknown as {delta: number}).delta, -1, resource.reference);
Object.assign(animation, {renderer});
animation.advance(0);
assert.equal(renderer.meshes.length, 3);
const initial = renderer.meshes.map(mesh => [...mesh.getVerticesData(VertexBuffer.PositionKind)!]);
for (let frame = 0; frame < 30; frame++) animation.advance(1 / 60);
assert(renderer.meshes.some((mesh, index) => mesh.getVerticesData(VertexBuffer.PositionKind)!.some((v, i) => v !== initial[index][i])));
assert(renderer.meshes.every((mesh, index) => mesh.metadata.sourceSceneModel === resource.reference && mesh.metadata.sourceSceneModelNode === index && mesh.name === `placement-32/cvd-${index}`));
animation.dispose();
assert.equal(scene.meshes.length, 0);
scene.dispose();engine.dispose();
console.log('PASS: original0007 General32 three animated source geometries, strict loop boundary, thirty-frame metadata/vertex changes and disposal');
