import assert from 'node:assert/strict';
import {spawn,type ChildProcess} from 'node:child_process';
import {mkdtempSync,rmSync,writeFileSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {WsClient} from 'tsrpc';
import {serviceProto} from '../apps/shared/protocols/serviceProto';
import {AccountStore} from '../apps/server/src/account-store';
import type {MsgRoomSnapshot,MsgRoomEvent} from '../apps/shared/protocols';
async function main(){
 
 const runId=new Date().toISOString().replace(/[:.]/g,'-'),output='recovery/output/tank-purchase-network-'+runId,dir=mkdtempSync(join(tmpdir(),'cdtank-tank-purchase-')),database=join(dir,'accounts.sqlite'),port=3240;let server:ChildProcess|undefined,log='';
 const clients=Array.from({length:4},()=>new WsClient(serviceProto,{server:`ws://127.0.0.1:${port}`,logger:undefined,heartbeat:{interval:5000,timeout:10000}}));const snapshots:MsgRoomSnapshot[][]=clients.map(()=>[]),events:MsgRoomEvent[][]=clients.map(()=>[]),timed:{page:number;tick:number;receivedAt:number;event:MsgRoomEvent}[]=[];clients.forEach((c,i)=>{c.listenMsg('RoomSnapshot',s=>{snapshots[i].push(s);});c.listenMsg('RoomEvent',e=>{events[i].push(e);timed.push({page:i,tick:snapshots[i].at(-1)?.tick??0,receivedAt:Date.now(),event:e});});});
 async function wait(f:()=>boolean,ms=10000){const end=Date.now()+ms;while(!f()&&Date.now()<end)await new Promise(r=>setTimeout(r,25));assert(f(),log.slice(-1000));}async function stop(){if(server?.exitCode===null&&server.signalCode===null){const end=new Promise<void>(r=>server!.once('exit',()=>r()));server.kill();await end;}}async function start(){const startOffset=log.length;server=spawn(process.execPath,['--import','tsx','apps/server/src/index.ts'],{env:{...process.env,PORT:String(port),ACCOUNT_DB_PATH:database,MATCH_TIME_LIMIT_SECONDS:'30'},stdio:['ignore','pipe','pipe']});server.stdout!.on('data',d=>{log+=String(d);});server.stderr!.on('data',d=>{log+=String(d);});await wait(()=>log.slice(startOffset).includes(`Server started at ${port}.`));}
 const latest=(i=0)=>snapshots[i].at(-1)!;const evidence:{[key:string]:unknown}={status:'RUNNING',runId,port,scope:'Rebuilt source tankshop3 mode2 MONEY2500 BUY-created ownership, explicit existing pet1/tank1 and funds3000/2000 fixtures; authenticated transactions/OwnedRoles/SelectRole/normal tank3 move-fire versusCPU/Leave/sameDB original-token restore; no preownedtank3 or runtime injection'};
 try{
 await start();const accounts:{accountId:string;token:string}[]=[];for(const c of clients.slice(0,3)){assert((await c.connect()).isSucc);const a=await c.callApi('Account',{});assert(a.isSucc);accounts.push(a.res);}
 const template=JSON.parse(readFileSync('recovery/output/world-role-attributes-native.json','utf8')).rows.find((r:{tankId:number;part:number})=>r.tankId===1&&r.part===0);const store=new AccountStore(database);
 const base=new Map<number,number>(Object.keys(template.base).map(k=>[Number(k),0])),equipment=new Map<number,number>(Object.keys(template.equipment).map(k=>[Number(k),0]));base.set(0,73);base.set(8,1);base.set(0x2c,600);base.set(0x34,5);base.set(0x3c,10);equipment.set(0x1c,74);equipment.set(0x24,1);equipment.set(0x3c,100);equipment.set(0x40,70);equipment.set(0x4c,15);equipment.set(0x50,30);equipment.set(0x58,2001);
 try{for(const [i,account]of accounts.slice(0,2).entries()){store.replaceRoleRecords(account.accountId,{base:[{name:'Explicit base pet1 fixture',fields:base}],equipment:[{name:'Explicit base tank1 fixture',fields:equipment}]});assert.equal(store.inventory(account.accountId).records.length,0);const bytes=new Uint8Array(0x170),view=new DataView(bytes.buffer);view.setUint32(0xa4,73,true);view.setUint32(0xa8,74,true);view.setUint32(0x70,i===0?3000:2000,true);view.setUint32(0x74,1000,true);store.replaceRoleProfile(account.accountId,{bytes,strings:['','']});}}finally{store.close();}
 evidence.fixture={source:'explicit previously measured sourcepet1HP600/tank1 complete layout',base:[...base],equipment:[...equipment],money:[3000,2000],tokens:1000,initialOwnedTank3:false};
 assert((await clients[3].connect()).isSucc);const unauth=await clients[3].callApi('TankShop',{operation:'QUERY'});assert(!unauth.isSucc&&unauth.err.code==='ACCOUNT_REQUIRED');evidence.unauthenticated=unauth;
 const query=await clients[0].callApi('TankShop',{operation:'QUERY'});assert(query.isSucc);const originalTank3=query.res.tanks.find(t=>t.tankId===3)!;assert(originalTank3);assert.equal(originalTank3.moneyPrice,2500);assert.equal(originalTank3.tokenPrice,250);evidence.catalog=query.res;const request={operation:'BUY' as const,tankId:3,currency:'MONEY' as const,requestId:'tank3_money_0001'};
 const token=await clients[0].callApi('TankShop',{...request,currency:'TOKENS',requestId:'tank3_token_0001'});assert(!token.isSucc);const invalid=await clients[0].callApi('TankShop',{...request,tankId:2,requestId:'tank3_invalid_0001'});assert(!invalid.isSucc);const shortage=await clients[1].callApi('TankShop',{...request,requestId:'tank3_shortage_0001'});assert(!shortage.isSucc);const badRequestId=await clients[0].callApi('TankShop',{...request,requestId:'x'});assert(!badRequestId.isSucc);evidence.rejected={token,invalid,shortage,badRequestId};
 const paid=await clients[0].callApi('TankShop',request);assert(paid.isSucc);assert.equal(paid.res.money,500);assert.equal(paid.res.tokens,1000);const bought=paid.res.purchased!,fields=new Map(bought.fields),instanceId=fields.get(0x1c)!;assert(instanceId!==74);assert.equal(fields.get(0x24),3);assert.deepEqual([fields.get(0x28),fields.get(0x2c),fields.get(0x30)],[30041,30042,30013]);assert.deepEqual([fields.get(0x3c),fields.get(0x40),fields.get(0x4c),fields.get(0x50)],[122,78,17,44]);for(const [offset,value]of fields)if(![0x1c,0x24,0x28,0x2c,0x30,0x3c,0x40,0x4c,0x50].includes(offset))assert.equal(value,0);evidence.purchase=paid.res;
 const replay=await clients[0].callApi('TankShop',request);assert(replay.isSucc&&replay.res.replayed&&replay.res.money===500);assert.deepEqual(replay.res.purchased,bought);const conflict=await clients[0].callApi('TankShop',{...request,currency:'TOKENS'});assert(!conflict.isSucc);evidence.idempotency={replay,conflict};
 const owned=await clients[0].callApi('OwnedRoles',{});assert(owned.isSucc);assert.equal(owned.res.equipment.length,2);assert.deepEqual(owned.res.equipment.find(r=>new Map(r.fields).get(0x1c)===instanceId),bought);const peerOwned=await clients[1].callApi('OwnedRoles',{});assert(peerOwned.isSucc&&peerOwned.res.equipment.length===1);const peerBalance=await clients[1].callApi('TankShop',{operation:'QUERY'});assert(peerBalance.isSucc&&peerBalance.res.money===2000&&peerBalance.res.tokens===1000);const peerSelect=await clients[1].callApi('SelectRole',{kind:'tank',instanceId});assert(!peerSelect.isSucc);evidence.accountIsolation={peerOwned:peerOwned.res,peerBalance:peerBalance.res,peerSelect};
 const profileBefore=await clients[0].callApi('RoleProfile',{});assert(profileBefore.isSucc);assert.equal(new DataView(Uint8Array.from(profileBefore.res.profile!.bytes).buffer).getUint32(0xa8,true),74);const selected=await clients[0].callApi('SelectRole',{kind:'tank',instanceId});assert(selected.isSucc);assert.equal(new DataView(Uint8Array.from(selected.res.profile.bytes).buffer).getUint32(0xa8,true),instanceId);evidence.selected=selected.res;
 const created=await clients[0].callApi('CreateRoom',{mode:4,mapId:7,name:'购买战车',tankId:3,roomName:'付费战车'});evidence.created=created;assert(created.isSucc);const roomId=created.res.room.id,ownerId=created.res.playerId;const cpu=await clients[0].callApi('Cpu',{round:1,operation:'ADD',tankId:1});assert(cpu.isSucc);assert((await clients[0].callApi('Ready',{round:1,isReady:true})).isSucc);await wait(()=>latest()?.phase==='PLAYING');evidence.initial=latest();const player=()=>latest().players.find(p=>p.id===ownerId)!;assert.equal(player().tankId,3);assert.deepEqual(player().tankTextures,{U:30041,M:30042,XY:30013});
 const gated=await clients[0].callApi('TankShop',{...request,requestId:'tank3_playing_0001'});assert(!gated.isSucc);evidence.playingReject=gated;
 const before=player();assert((await clients[0].sendMsg('PlayerInput',{sequence:1,move:1,turn:0,aim:0,fire:false,useItem:0,clientTime:Date.now()})).isSucc);const until=latest().tick+20;await wait(()=>latest().tick>=until);const after=player();assert(Math.hypot(after.x-before.x,after.z-before.z)>0.1);assert((await clients[0].sendMsg('PlayerInput',{sequence:2,move:0,turn:0,aim:0,fire:true,useItem:0,clientTime:Date.now()})).isSucc);await wait(()=>events[0].some(e=>e.type==='fire'&&e.playerId===ownerId));assert((await clients[0].sendMsg('PlayerInput',{sequence:3,move:0,turn:0,aim:0,fire:false,useItem:0,clientTime:Date.now()})).isSucc);evidence.normalBattle={before,after,fire:events[0].find(e=>e.type==='fire'&&e.playerId===ownerId),latest:latest()};assert((await clients[0].callApi('Leave',{roomId,round:1})).isSucc);
 await Promise.all(clients.map(c=>c.disconnect()));await stop();await start();assert((await clients[0].connect()).isSucc);assert((await clients[0].callApi('Account',{token:accounts[0].token})).isSucc);const restoredOwned=await clients[0].callApi('OwnedRoles',{});assert(restoredOwned.isSucc);assert.deepEqual(restoredOwned.res.equipment.find(r=>new Map(r.fields).get(0x1c)===instanceId),bought);const restoredProfile=await clients[0].callApi('RoleProfile',{});assert(restoredProfile.isSucc);assert.equal(new DataView(Uint8Array.from(restoredProfile.res.profile!.bytes).buffer).getUint32(0xa8,true),instanceId);const restoredBalance=await clients[0].callApi('TankShop',{operation:'QUERY'});assert(restoredBalance.isSucc&&restoredBalance.res.money===500&&restoredBalance.res.tokens===1000);evidence.actualRestart={owned:restoredOwned.res,profile:restoredProfile.res,money:restoredBalance.res.money,tokens:restoredBalance.res.tokens};evidence.status='PASS';console.log(JSON.stringify({status:'PASS',output,instanceId,money:500}));
 }catch(error){evidence.status='FAIL';evidence.error=String(error);throw error;}finally{evidence.snapshots=snapshots;evidence.events=events;evidence.timed=timed;await Promise.allSettled(clients.map(c=>c.disconnect()));await stop();writeFileSync(output+'.json',JSON.stringify(evidence,null,2)+'\n');writeFileSync(output+'.log',log);rmSync(dir,{recursive:true,force:true});}
}main().catch(e=>{console.error(e);process.exitCode=1;});
