import type {OwnedRoleBaseRecord} from '../../../shared/contracts/owned-base';
import type {EquipmentSupplyState} from './items/equipment-supply';
import type {LastStandState} from './last-stand';
import type {TrapFireRestraintState} from './items/trap-fire-restraint';
import type {TrapTurnRestraintState} from './items/trap-turn-restraint';
import type {TrapRestraintState} from './items/trap-restraint';
import type {recomputeQualifiedRoleArmor} from './roles/recompute-armor';
import type {AmmoBurnState} from './items/ammo-burn';
import type {AmmoSlowState} from './items/ammo-slow';
import type {DefenseBoostState} from './items/defense-drink';
import type {RoleMovementMathInput} from './roles/movement-math';
import type {BattleMovementState} from './movement';
import type {TankConfig} from '../config';
import type {RoleCombatState} from './roles/combat-state';
import type {InventoryWireRecord} from '../../../shared/protocols/PtlInventory';
import type {BattleRoleSources} from '../battle-role-sources';
import type {RoleAttributeState} from './roles/attribute-state';
import type {MsgPlayerInput} from '../../../shared/protocols';
import type {BotController} from './cpu/controller';
import type {AttackBoostState} from './items/attack-drink';
import type {TurnBoostState} from './items/turn-drink';
import type {SpeedBoostState} from './items/speed-drink';
import type {InvincibilityState} from './items/invincibility';
import type {OpticalCamouflageState} from './items/optical-camouflage';
import type {RoleDisguiseState} from './items/role-disguise';
import type {PetHitSpeedState} from './pet-hit-speed';
import type {ShotModifiers} from './roles/shot-modifiers';
import type {PlayerTitle, RoundStats} from '../../../shared/protocols/MsgRoomSnapshot';

export interface PlayerState {
  id: string;
  clientId: string;
  name: string;
  tank: TankConfig;
  team: number;
  x: number;
  y: number;
  z: number;
  yaw: number;
  bodyYaw?: number;
  movementState?: BattleMovementState;
  movementCommand?: RoleMovementMathInput['command'];
  aim: number;
  hp: number;
  alive: boolean;
  score: number;
  kills: number;
  deaths: number;
  respawnAt: number;
  cancellationsSpent: number;
  equipmentSupply?: EquipmentSupplyState;
  lastStand?: LastStandState;
  combat: RoleCombatState;
  inventory: InventoryWireRecord[];
  ownedRoles: BattleRoleSources;
  boundGear?: OwnedRoleBaseRecord;
  attributes: RoleAttributeState;
  attributesReady: boolean;
  magazineReady: boolean;
  armorReady?: boolean;
  recoveredArmor?: ReturnType<typeof recomputeQualifiedRoleArmor>;
  lifeReady?: boolean;
  recoveredMaxHp?: number;
  recoveredMovement?: {speed: number; turn: number};
  shotModifiers?: ShotModifiers;
  attackBoost?: AttackBoostState;
  defenseBoost?: DefenseBoostState;
  trapRestraint?: TrapRestraintState;
  trapTurnRestraint?: TrapTurnRestraintState;
  trapFireRestraint?: TrapFireRestraintState;
  burn?: AmmoBurnState;
  ammoSlow?: AmmoSlowState;
  invincibility?: InvincibilityState;
  opticalCamouflage?: OpticalCamouflageState;
  roleDisguise?: RoleDisguiseState;
  speedBoost?: SpeedBoostState;
  turnBoost?: TurnBoostState;
  petHitSpeed?: PetHitSpeedState;
  inputSequence: number;
  input: MsgPlayerInput;
  vip: boolean;
  objectivesDestroyed: number;
  /** Real per-round producers; absent only on legacy fixtures without a battle path. */
  roundStats?: RoundStats;
  /** Current no-death kill streak during the round; the frozen maximum lives on roundStats. */
  roundCurrentKillCombo?: number;
  /** Shot identities already charged to hits, so one shot credits at most one hit. */
  roundHitShotIds?: Set<string>;
  cpu?: BotController;
  autopilot?: BotController;
  autopilotInputSequence?: number;
  /** Authoritative account-owned worn title projected from AccountStore; absent means none shown. */
  title?: PlayerTitle;
}
