import type {BattleVectorShape} from './battle-screen-vectors';

/** Original published combat digit and Critical/Combo artwork. */
export const BATTLE_TEXT_VECTORS: Readonly<Record<string, BattleVectorShape>> = {
  "ui/regions/9/1.png": {"width":24,"height":28,"asset":"ui/regions/9/1.png"},
  "ui/regions/9/9.png": {"width":18,"height":28,"asset":"ui/regions/9/9.png"},
  "ui/regions/9/6.png": {"width":21,"height":28,"asset":"ui/regions/9/6.png"},
  "ui/regions/9/7.png": {"width":20,"height":28,"asset":"ui/regions/9/7.png"},
  "ui/regions/9/2.png": {"width":24,"height":28,"asset":"ui/regions/9/2.png"},
  "ui/regions/9/8.png": {"width":20,"height":28,"asset":"ui/regions/9/8.png"},
  "ui/regions/9/3.png": {"width":24,"height":28,"asset":"ui/regions/9/3.png"},
  "ui/regions/9/4.png": {"width":24,"height":28,"asset":"ui/regions/9/4.png"},
  "ui/regions/9/0.png": {"width":25,"height":28,"asset":"ui/regions/9/0.png"},
  "ui/regions/9/5.png": {"width":24,"height":28,"asset":"ui/regions/9/5.png"},
  "ui/regions/7/1.png": {"width":24,"height":28,"asset":"ui/regions/7/1.png"},
  "ui/regions/7/9.png": {"width":18,"height":28,"asset":"ui/regions/7/9.png"},
  "ui/regions/7/6.png": {"width":21,"height":28,"asset":"ui/regions/7/6.png"},
  "ui/regions/7/7.png": {"width":20,"height":28,"asset":"ui/regions/7/7.png"},
  "ui/regions/7/2.png": {"width":24,"height":28,"asset":"ui/regions/7/2.png"},
  "ui/regions/7/8.png": {"width":20,"height":28,"asset":"ui/regions/7/8.png"},
  "ui/regions/7/3.png": {"width":24,"height":28,"asset":"ui/regions/7/3.png"},
  "ui/regions/7/4.png": {"width":24,"height":28,"asset":"ui/regions/7/4.png"},
  "ui/regions/7/0.png": {"width":25,"height":28,"asset":"ui/regions/7/0.png"},
  "ui/regions/7/5.png": {"width":24,"height":28,"asset":"ui/regions/7/5.png"},
  "ui/regions/1/1.png": {"width":24,"height":28,"asset":"ui/regions/1/1.png"},
  "ui/regions/1/9.png": {"width":18,"height":28,"asset":"ui/regions/1/9.png"},
  "ui/regions/1/6.png": {"width":21,"height":28,"asset":"ui/regions/1/6.png"},
  "ui/regions/1/7.png": {"width":20,"height":28,"asset":"ui/regions/1/7.png"},
  "ui/regions/1/2.png": {"width":24,"height":28,"asset":"ui/regions/1/2.png"},
  "ui/regions/1/8.png": {"width":20,"height":28,"asset":"ui/regions/1/8.png"},
  "ui/regions/1/3.png": {"width":24,"height":28,"asset":"ui/regions/1/3.png"},
  "ui/regions/1/4.png": {"width":24,"height":28,"asset":"ui/regions/1/4.png"},
  "ui/regions/1/0.png": {"width":25,"height":28,"asset":"ui/regions/1/0.png"},
  "ui/regions/1/5.png": {"width":24,"height":28,"asset":"ui/regions/1/5.png"},
  "ui/regions/8/1.png": {"width":24,"height":28,"asset":"ui/regions/8/1.png"},
  "ui/regions/8/9.png": {"width":18,"height":28,"asset":"ui/regions/8/9.png"},
  "ui/regions/8/6.png": {"width":21,"height":28,"asset":"ui/regions/8/6.png"},
  "ui/regions/8/7.png": {"width":20,"height":28,"asset":"ui/regions/8/7.png"},
  "ui/regions/8/2.png": {"width":24,"height":28,"asset":"ui/regions/8/2.png"},
  "ui/regions/8/8.png": {"width":20,"height":28,"asset":"ui/regions/8/8.png"},
  "ui/regions/8/3.png": {"width":24,"height":28,"asset":"ui/regions/8/3.png"},
  "ui/regions/8/4.png": {"width":24,"height":28,"asset":"ui/regions/8/4.png"},
  "ui/regions/8/0.png": {"width":25,"height":28,"asset":"ui/regions/8/0.png"},
  "ui/regions/8/5.png": {"width":24,"height":28,"asset":"ui/regions/8/5.png"},
  "ui/regions/44/9.png": {"width":128,"height":99,"asset":"ui/regions/44/9.png"},
  "ui/regions/44/11.png": {"width":110,"height":82,"asset":"ui/regions/44/11.png"},
  "ui/regions/77/9.png": {"width":128,"height":99,"asset":"ui/regions/77/9.png"},
  "ui/regions/77/11.png": {"width":110,"height":82,"asset":"ui/regions/77/11.png"},
};
