"""Record original Shop description type setter and its table-text dependency."""
import json
from pathlib import Path
import pefile,capstone
ROOT=Path(__file__).resolve().parents[3];pe=pefile.PE(str(ROOT/'CDTank/CDTank.exe'));base=pe.OPTIONAL_HEADER.ImageBase
cs=capstone.Cs(capstone.CS_ARCH_X86,capstone.CS_MODE_32)
def trace(a,z):return [{'va':hex(i.address),'asm':i.mnemonic+' '+i.op_str} for i in cs.disasm(pe.get_data(a-base,z-a),a)]
assert pe.get_data(0x5d6b84-base,60).split(b'\0')[0]==b'ShopEquipPageItemPanel/txtType'
result={'status':'ORIGINAL_TYPE_TEXT_CONFIRMED_SAME_ITEM_NAME_GETTER_OUTPUT','tasks':['UI52','M5-10'],'control':'ShopEquipPageItemPanel/txtType','controlString':'5d6b84','ownerMember':'80','controlInitialization':trace(0x513be2,0x513c2c),'selectedItemAndLookup':trace(0x514500,0x51456e),'originalTypeSetter':trace(0x514623,0x51467e),'typeGetter':trace(0x4d7e58,0x4d7e7c),'tableLookup':trace(0x43bda2,0x43bdbd),'tableOwner':trace(0x413c74,0x413c83),'stringConverter':'412649','descriptionGetter':trace(0x4d7dec,0x4d7e10),'confirmed':'Selection row+9c selects a record through43bda2→413c74→411068. Description reads string at record+34; txtType reads distinct string at record+14 via4d7e58, then Window.setText.','getterOutputIdentity':{'homeCaller':trace(0x4d8366,0x4d838a),'homeFactory':trace(0x4e2fb0,0x4e301b),'weaponFactory':trace(0x4e4d74,0x4e4de1),'homeArgument':'MyItem+0c itemTableId resolves43bda2; EAX record is pushed directly to4d7e58 with caller destination. Only stack cleanup follows; no transformation.','shopArgument':'Selected row+9c itemTableId resolves same43bda2->413c74->411068 and stores EAX at[ebp+8];514655 pushes same record directly to4d7e58 and51466c sets its destination string.','table':'Both return from[[633588]+114]+7c table+0c map411068.','verifiedCurrentProvider':'export_combat_catalog.py ItemName->catalog.name; ShopQUERY sends existing name.','producerReuse':'Same original name getter output as accepted Home primary name column; use current selectedproduct.name without a new protocol field.'},'missing':'Full native table loader reconstruction and original string encoding precision remain outside this getter-output identity scope.','limits':['Do not substitute classifyItemId/gamestring685 type labels: this setter consumes original table text.','Existing accepted four-control description/QUERY/Close scope remains valid.','No production changed or new actual run; next consumer may bind only existing selectedproduct.name.']}
(ROOT/'recovery/output/shop-description-type-source.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n')
print(result['status'])
