"""Original Shop Valuable radio and current formal QUERY boundary."""
import json
from pathlib import Path
import pefile,capstone
ROOT=Path(__file__).resolve().parents[3];p=pefile.PE(str(ROOT/'CDTank/CDTank.exe'));base=p.OPTIONAL_HEADER.ImageBase;c=capstone.Cs(capstone.CS_ARCH_X86,capstone.CS_MODE_32)
def trace(a,z):return [{'va':hex(i.address),'asm':i.mnemonic+' '+i.op_str} for i in c.disasm(p.get_data(a-base,z-a),a)]
assert p.get_data(0x5cc22c-base,80).split(b'\0')[0]==b'ConvenientPage/rdoShopValuablePage'
raw='recovery/output/browser-shop-owned-sale-display-2026-10-05T12-05-40-551Z.json';r=json.loads((ROOT/raw).read_text());query=next(n['response']['items'] for n in r['network'] if n['direction']=='received' and n['name']=='Shop' and n.get('success'));valuable=[v for v in query if 20001<=v['itemTableId']<=22000];assert not valuable
out={'status':'SOURCE_READY_RIGHT_VALUABLE_NAVIGATION_CURRENT_QUERY_EMPTY_BOUNDARY','tasks':['UI53','M5-10'],'sourceControl':'ConvenientPage/rdoShopValuablePage','initialization':trace(0x49ec6c,0x49eca4),'ownerMember':'0x5c','callback':'4a03c7 selectedWindow handler','valuableCallback':trace(0x4a0766,0x4a07bf),'categoryEligibility':'4396e0==6; same formal classifyInventoryCategory existing source implementation','factory':trace(0x4a07ab,0x4a0927),'nativePositiveRowBranches':{'eligible4396c2':'4a0896->4b9251','otherCategory6':'4a08db->4ba7df'},'currentFormalQuery':{'raw':raw,'totalRecords':len(query),'category6Records':0,'noRecordFabrication':True},'proposal':'Restore only original rightValuable radio selection->category6 filtering->realcurrentempty source list->normalItemreturn/Close. Preserve original availability gap/current QUERY/BUY policy. Handle selectedundefined refresh with currentcategory ref; no positiveValuable row acceptance.','producerGaps':['Current formal QUERY has no category6 products; original availability authority not established.','Original otherCategory6 row4ba7df/type content remains an unconsumed positive branch.','OwnedValuable radio parentfactory dispatch is not proven by this bounded source; keep it disabled and separate.'],'productionChanged':False,'chromeStarted':False}
(ROOT/'recovery/output/shop-valuable-navigation-source.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print(out['status'])
