export const tankThumbnails: Readonly<Record<string, string>> = {
  '001': '/local-images/assets/tanks/thumbnails/001.png',
  '002': '/local-images/assets/tanks/thumbnails/002.png',
  '003': '/local-images/assets/tanks/thumbnails/003.png',
  '004': '/local-images/assets/tanks/thumbnails/004.png',
  '051': '/local-images/assets/tanks/thumbnails/051.png',
  '052': '/local-images/assets/tanks/thumbnails/052.png',
  '053': '/local-images/assets/tanks/thumbnails/053.png',
  '054': '/local-images/assets/tanks/thumbnails/054.png',
  '101': '/local-images/assets/tanks/thumbnails/101.png',
  '102': '/local-images/assets/tanks/thumbnails/102.png',
  '103': '/local-images/assets/tanks/thumbnails/103.png',
  '104': '/local-images/assets/tanks/thumbnails/104.png',
  '105': '/local-images/assets/tanks/thumbnails/105.png',
  '151': '/local-images/assets/tanks/thumbnails/151.png',
  '152': '/local-images/assets/tanks/thumbnails/152.png',
  '153': '/local-images/assets/tanks/thumbnails/153.png',
  '154': '/local-images/assets/tanks/thumbnails/154.png',
  '155': '/local-images/assets/tanks/thumbnails/155.png',
  '156': '/local-images/assets/tanks/thumbnails/156.png',
  '157': '/local-images/assets/tanks/thumbnails/157.png',
  '158': '/local-images/assets/tanks/thumbnails/158.png',
};
