/** Accepted shortcut request; authority and item consumption belong to the server. */
export interface ItemUseRequest {
  kind: 'placeTrap' | 'useItem';
  instanceId: number;
}

export interface PlaySkillEffectMessage {
  skillId: number;
  effectIndex: number;
  duration: number;
  roleId: number;
  /** Original X/Z float payloads; roleId0 selects the world-position branch. */
  xBits: number;
  zBits: number;
}

export interface StopSkillEffectMessage {
  skillId: number;
  roleId: number;
}

/** Original immediate scene/free-aim display, separate from projectile hits. */
export interface ShotDisplayMessage {
  itemId: number;
  x: number;
  y: number;
  z: number;
}

export interface MsgRoomEvent {
  roomId: string;
  type: string;
  message: string;
  playerId: string;
  targetId: string;
  value: number;
  x: number;
  y: number;
  z: number;
  /** Original skill table ID for a confirmed fire/cast event; absent for unrelated events. */
  skillId?: number;
  /** Original actor hurt parameter 1..4 selects source actions05..08; omitted without a classified hit. */
  hurtSelector?: number;
  /** Original scene/free display dispatch; query geometry remains reconstructed. */
  shotDisplay?: ShotDisplayMessage;
  /** Accepted shot result; ammo is frozen by rebuilt authority, not an original3aa3 wire field. */
  shotPlayerResult?: {itemId: number; critical?: boolean};
  /** Source scene result display; server destruction eligibility and endpoint mapping are rebuilt. */
  shotItemResult?: ShotDisplayMessage;
  /** One accepted Castle damage transaction; source presentation is not snapshot-driven. */
  /** Accepted original ShotItem Crush branch; snapshots never replay its effect. */
  sceneCrush?: {placementId: string};
  /** Original static type100 Plant hide; no shot feedback or optional effect replay. */
  scenePlant?: {placementId: string};
  castleDamage?: {castleId: string; currentHP: number; maxHP: number; delta: number};
  /** Permitted shortcut request; does not confirm casting or quantity consumption. */
  itemUseRequest?: ItemUseRequest;
  /** Decoded original notifications, generated by authoritative skill resolution. */
  playSkillEffect?: PlaySkillEffectMessage;
  stopSkillEffect?: StopSkillEffectMessage;
}
